### ISSUE TITLE
Riemann metrics support

### ISSUE THREAD

**Issue by robholland** [fabiolb/fabio#126]
Will you accept PRs adding support for new metric targets (new go-metric modules)? It's not really clear to me what the implications of that are for you as a maintainer.

**Comment by magiconair** [comment]
Yes. There shouldn't be any implications other than the config management. I'd only ask you to base your changes on the 1.2 branch since I'm merging that shortly.

**Comment by magiconair** [comment]
@robholland I've added support for Riemann metrics but the driver I've found (github.com/pingles/go-metrics-riemann) pulls quite a lot of baggage. Did you have a different driver in mind? In any case it would be cool if you could test that.

**Comment by robholland** [comment]
That was the driver I had in mind. As I've mentioned in the other issue we won't be able to do any testing for a bit, as riemann is perhaps a little obscure and it carries more deps than you'd like I'd suggest just drop it. When/if we come back to experimenting with fabio I'll pick it back up.

Thanks for all your help.

**Comment by magiconair** [comment]
Then I'll leave this here until someone else wants this. It isn't a big deal to merge but the deps are a bit dated ...

**Comment by magiconair** [comment]
If someone else wants this then please +1

**Comment by magiconair** [comment]
Rebased this on #147

**Comment by magiconair** [comment]
Rebased on master.

**Comment by magiconair** [comment]
Please see https://github.com/fabiolb/fabio/issues/211#issuecomment-375880738
