### ISSUE TITLE
Question: Support for Consul v0.7.3 Node tags

### ISSUE THREAD

**Issue by gamefundas** [fabiolb/fabio#252]
Is there a plan to support Node tags which was recently added to Consul 0.7.3?

The real requirement for me is to be able able to route my calls to individual nodes in my service cluster. For example if Service-A has Node 1, 2, 3 then I would like to access them directly (non-loadbalanced way) via 

http://fabio.host:port/service-A/node1
http://fabio.host:port/service-A/node2
http://fabio.host:port/service-A/node3

Even if the node names are numerical sequence it should be fine. We just need the ability to access the nodes via the fabio proxy.

I tried implementing this using consul-template + Nginx but came across fabio which seems to be doing most of the work for me in a simple plug and play manner. Would love to know if this feature can be implemented in some way.

**Comment by magiconair** [comment]
I'm wondering whether this is related to #101 (sticky load balancing).

**Comment by gamefundas** [comment]
I don't think this is related to #101 or sticky sessions. Perhaps my explanation is misleading.

In my scenario, fabio is able to create a load balanced route http://fabio.host:port/service-A
and accessing that lands me in one of the nodes. But what I need is the ability to hit Node-1, Node-2 and Node-3 independently.

**Comment by gamefundas** [comment]
Mine is not really a load balancing use case. Its merely routing calls to specific nodes. We have maintenance service endpoints on each nodes that requires us to reach the specific faulty node to either restart or perform basic support operations like purge cache etc. A load balancer would randomly route the call. We would like to target the faulty nodes and be able to hit the specific host. 

Instead of numerical sequence, host names will also work.

**Comment by magiconair** [comment]
Why don't you just announce a unique route for that host, e.g. `urlprefix-/admin/$HOSTNAME`?

**Comment by gamefundas** [comment]
This might work. Didn't think that I could very much control how to create my route path.
Thanks. 

Closing this one.

**Comment by magiconair** [comment]
You would need to have a handler for that on the upstream server though
