### ISSUE TITLE
Support Consul TLS

### ISSUE THREAD

**Issue by sethvargo** [fabiolb/fabio#276]
Currently only specifying the address is allowed, but there are many other options for Consul TLS like the CA file, key, and cert.

**Comment by erenfro** [comment]
I definitely need this as well.

**Comment by erenfro** [comment]
In my test environment, I had a very simple consul setup. But in my main environment where I was going to deploy fabio, consul is setup to be fully encrypting gossip and tls communications, which for fabio that means it won't work, at all.

**Comment by leprechau** [comment]
@sethvargo Sorry if this got put to the backlog.  Is this still something that's needed mainline in fabio?  Sorry for asking a redundant question if this has already be covered elsewhere.

**Comment by vjeantet** [comment]
Hello, need this too, deployment compromised.

How can we help to see fabio able to connect to consul via TLS and TLS with client connect ?

**Comment by magiconair** [comment]
@vjeantet I think the patch from @jen20 looks OK. If you can rebase that for master then we can merge it.
