### ISSUE TITLE
Add service name to access log fields

### ISSUE THREAD

**Issue by Spicykoala** [fabiolb/fabio#278]
I have a use case where I'm parsing the streamed access logs to calculate request statistics on a more granular level than the metrics output gives. I have no issues with this but, given a path that is split between two services - I can't figure out a way (other than keeping track of all of the service ips) to track which *service* the request is headed towards. Is this available at the time the access log is being created? 

If not, any ideas or clever ways to workaround this?

Thanks for the awesome lb!

**Comment by magiconair** [comment]
Thanks. I'm glad you like it :)

I've added a patch which should do what you want. This sounds like a good idea and the metrics should probably expose that as well. Could you let me know whether that works for you?

**Comment by magiconair** [comment]
Erm, the metrics already export this. Time for ☕️ Enjoy 😄

**Comment by Spicykoala** [comment]
Perfect. That's exactly what I was looking for! Enjoy I shall.

**Comment by Spicykoala** [comment]
I realized I should probably leave this open until it's merged in :)

**Comment by magiconair** [comment]
yeah ;) it is merged now. Have fun
