### ISSUE TITLE
chunked Transfer-Encoding

### ISSUE THREAD

**Issue by jamesdmorgan** [fabiolb/fabio#284]
Hi,

We are running 1.3.5-go1.7.4 and seeing that certain requests to fabio are getting truncated.

When hitting the app locally we get

Content-Length: 884583

```
 GET /blog/ghost/ghost.min.js?v=334f28ea38 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.128.194.233:50438
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.9.11
< Date: Thu, 04 May 2017 14:59:17 GMT
< Content-Type: application/javascript
< Content-Length: 884583
< Connection: keep-alive
< X-Powered-By: Express
< Accept-Ranges: bytes
< Cache-Control: public, max-age=31536000
< Last-Modified: Thu, 12 Jan 2017 12:24:56 GMT
< ETag: W/"d7f67-15992a359c0"
< Vary: Accept-Encoding
```

via **Fabio** gives

Content-Length: 1643459

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=31536000
Content-Length: 1643459
Content-Type: application/javascript
Date: Thu, 04 May 2017 15:06:29 GMT
Etag: W/"1913c3-15992a359c0"
Last-Modified: Thu, 12 Jan 2017 12:24:56 GMT
Server: nginx/1.9.11
Vary: Accept-Encoding
X-Powered-By: Express
```

I plan on upgrading Fabio anyway as things have moved on just wondering if anybody had come across this recommend how to fix. 

Cheers

**Comment by magiconair** [comment]
I was going to say that 880Kb of JavaScript is more than enough until I saw that Fabio almost doubles it :) Please let me know what you find. This is the first time I hear about it.

**Comment by jamesdmorgan** [comment]
Good spot yeah that doesn't make any sense. I'll re-check thanks

**Comment by magiconair** [comment]
I don't see any compression headers. AFAIR, the Go http client automatically decompresses the response body. Can you check if the content is the same (md5 hash it to be sure)?

**Comment by jamesdmorgan** [comment]
I upgraded to the latest version and it works so i'll close this. Thanks for your help.
