### ISSUE TITLE
HTTPProxy cannot be aware of timeout of waiting response

### ISSUE THREAD

**Issue by silentred** [fabiolb/fabio#288]
In case using `httputil.ReverseProxy`, the error returned by RoundTrip(), is only recorded by Logger. https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L203 .

Therefore, it seems the HTTPProxy cannot distinguish whether it is a timeout or a normal response, when it tries to gather the metrics. https://github.com/fabiolb/fabio/blob/master/proxy/http_proxy.go#L134

Also, the backend service timeout causes the response have 502 code and without body. And the body cannot be customized right now. The worst is timeout error is not logged with enough context information, for example, which service or which URI gets timeout.

**Comment by magiconair** [comment]
I can always fork `httputil.ReverseProxy` and hack this in. Then file an issue with the Go team and hope for a future fix.

**Comment by magiconair** [comment]
What is the behavior you would like to see?

**Comment by magiconair** [comment]
Also, I'm already injecting a single-use round tripper which captures the `*http.Response` so that I can use it for access logging. I can capture the error there as well and handle it. 

https://github.com/fabiolb/fabio/blob/master/proxy/http_handler.go#L52-L64

**Comment by silentred** [comment]
Thanks. Another problem is ReverseProxy returns 502 without body to the client. I am hoping to customize the body according to each err type. It seems I have to copy ReverseProxy and make my own version. I wonder if there is a simpler way to achieve that.

**Comment by silentred** [comment]
I guess I found a work-around. Replace the out writer of `ErrorLog` in ReverseProxy with a custom one, which writes a JSON format body to the client. I am working on it.

**Comment by silentred** [comment]
I guess I found a work-around. Replace the out writer of `ErrorLog` in ReverseProxy with a custom one, which writes a JSON format body to the client. I am working on it.
