### ISSUE TITLE
Multiple SSL certs for same listener

### ISSUE THREAD

**Issue by tecnobrat** [fabiolb/fabio#291]
Does fabio provide a way to have multiple SSL certs attached to the same listener?

I would like to be able to have two wildcard certs, say `*.tugboat.zone` and `*.tugboat.info`, which point to the same fabio instance, and have them both work correctly.

Am I missing from the docs on how to make this work? Or is it not possible?

**Comment by magiconair** [comment]
Checkout the `path`, `consul`, `http` or `vault` cert store. They all support multiple certs based on SNI.

**Comment by tecnobrat** [comment]
I'm not sure I understand.  SNI makes the upstream handle the cert, does it not?

I'd like to handle the cert in fabio.

**Comment by tecnobrat** [comment]
I'm very confused, I can't find any example of multiple certs on the same listener in teh docs, so if you can point me in the right direction I'd be appreciative.

**Comment by magiconair** [comment]
https://github.com/fabiolb/fabio/blob/master/fabio.properties#L27-L51

You create a directory for the certificates and put them there. Then you configure a path cert source, e.g.

```
fabio -proxy.cs 'cs=ssl;type=path;cert=path/to/certs' -proxy.addr ':443;cs=ssl'
```

Then in `path/to/certs` you put

```
foo.com-cert.pem
foo.com-key.pem
bar.com.pem # contains both cert and key
```

For a request on port 443 fabio will check whether it can find a matching cert based on the server name.

**Comment by tecnobrat** [comment]
Oh crap, so `path` instead of `file`, and then fabio will do the magic! ... I was using `file`, and didn't realize that subtle difference.

Thanks muchly!

**Comment by tecnobrat** [comment]
That worked perfectly, thanks muchly.

**Comment by magiconair** [comment]
Cool. Glad I could help.
