### ISSUE TITLE
cert file names and path= not working as documented

### ISSUE THREAD

**Issue by manos** [fabiolb/fabio#293]
Hello,

1) if I set cs.proxy=type=path;path=/foo/bar, I get an error saying something like "map [...] cert not found." As in, it's expecting to find a cert= in the config line?

2) if my chain file (containing the cert) and key files are not named *.pem, fabio will fail to load the chain. I think it's reading just the first cert in the chain file, as it's not expecting to find multiple if the file name isn't .pem.

**Comment by magiconair** [comment]
1. Try `cert` instead of `path` https://github.com/fabiolb/fabio/blob/master/fabio.properties#L27-L51
2. yes, see docs in the same place about file name conventions.

**Comment by manos** [comment]
ok, all user error it looks like. I didn't read closely :)
