### ISSUE TITLE
logging health changes excludes useful info

### ISSUE THREAD

**Issue by manos** [fabiolb/fabio#295]
Hi,

When a service goes unhealthy, fabio seems to log: 
"Health changed to #753565"

It would be really handy to know _which_ service it's referring to. When debugging crashing backends, this would be super handy.

Is that possible to add? :) 
Thanks much!

**Comment by magiconair** [comment]
When this happens then the routing table changes and fabio should log the delta. The state change can also occur when there is no change in health but a change in the output of the health check. If you have volatile data like a timestamp or an ip address in the output then you can get a change like that without a routing table change.

You can run `consul monitor` to check what is going on in your cluster.

**Comment by manos** [comment]
Ooh, I think you're right. This is mostly happening when I see:
[INFO] agent: Synced check '2d2b8e084ac62d104f97b46a3eb1031e0de165da'

Thanks again :)
Loving fabio, by the way. It's working wonderfully.

**Comment by manos** [comment]
BTW, I'm not sure fabio should be logging anything unless the cluster state change impacts a service with urlprefix- tag(s), but knowing that I can ignore this is helpful.

**Comment by magiconair** [comment]
Although this isn't  a directly useful information for fabio it is for the operator as a secondary indicator for your cluster health. The usual problem - and you're not the first to ask - is to have either an unstable environment (which you should fix) or to have health check output with volatile data (your case) which puts stress on consul and the raft layer. 

I'm glad you like fabio. Please keep asking if there is anything that isn't clear.

**Comment by magiconair** [comment]
See https://github.com/fabiolb/fabio/issues/226 for example
