### ISSUE TITLE
Compatibility with 1.8

### ISSUE THREAD

**Issue by Superman132** [fabiolb/fabio#297]
Does this compile with go 1.8?

**Comment by magiconair** [comment]
Yes, It requires go1.8 :)

https://github.com/fabiolb/fabio#getting-started

**Comment by Superman132** [comment]
We should update the performance section with 1.8 metrics :)

**Comment by magiconair** [comment]
What do you mean?

**Comment by magiconair** [comment]
I'm closing this one but please feel free to comment.
