### ISSUE TITLE
Example of proxy.gzip.contenttype configuration

### ISSUE THREAD

**Issue by floekke** [fabiolb/fabio#299]
Hi

I'm looking for an example of a `proxy.gzip.contenttype` configuration in order to understand the regular expression syntax..

**Comment by magiconair** [comment]
You can use the one in `fabio.properties`:

https://github.com/fabiolb/fabio/blob/master/fabio.properties#L365-L380

**Comment by floekke** [comment]
Thank you!

**Comment by magiconair** [comment]
No problem :)
