### ISSUE TITLE
Support gzip compression for websockets

### ISSUE THREAD

**Issue by systemfreund** [fabiolb/fabio#300]
A browser (at least chrome does it) usually sends an `Accept-Encoding: gzip` header with every request. For example:

```
GET /some-websocket-endpoint HTTP/1.1
Connection: Upgrade
Upgrade: websocket
Accept-Encoding: gzip, deflate, sdch, br
```
Now I am running fabio with gzip compression enabled and when i execute the example request fabio responds with a 500 error. It's *not* the upstream server sending the 500, but fabio. The error response is sent from here:

https://github.com/fabiolb/fabio/blob/master/proxy/http_raw_handler.go#L28

The reason this is failing is that `w` can't by type-cast (or how it's called in Go slang) to an `http.Hijacker`, as `w` is a `GzipResponseWriter`.

I am not sure if it's a proper fix, but what I've done to make it work was to modify the `acceptsGzip` function like this:

```
func acceptsGzip(r *http.Request) bool {
	return (strings.Contains(r.Header.Get(headerAcceptEncoding), encodingGzip) &&
		!strings.Contains(r.Header.Get("Upgrade"), "websocket"))
}
```

**Comment by magiconair** [comment]
Is this on master? I think I've touched this code recently. I'll have a look later tonight.

**Comment by systemfreund** [comment]
Yes I can reproduce this on master

**Comment by systemfreund** [comment]
I was experimenting with master, because a similar issue regarding 500 errors and Websockets has been fixed recently and I was hoping that would solve my problem as it sounded very much like the same problem I am having. However, as you can see it was not the case.

**Comment by magiconair** [comment]
I'll fix that tonight

**Comment by magiconair** [comment]
I've pushed a fix that I think should fix this. Still need to write a test. Could you test this, please?

**Comment by systemfreund** [comment]
I appreciate your fast reaction! Unfortunately, the fix did not seem to help. For reference, I am running fabio with these parameters:

`./fabio  -proxy.gzip.contenttype='^(text/.*|application/(javascript|json|hal+json|xml)|.*\+(json|xml))(;.*)?$'`

Then I am doing the problematic request:

`nc localhost 9999 < /failing-request`

```
GET /channel2/sockjs/564/c4dvdxat/websocket HTTP/1.1
Host: localhost:9999
Connection: Upgrade
Upgrade: websocket
Accept-Encoding: gzip, deflate, sdch, br
```

I've added a fmt.Println() at the same location described above (http_raw_handler.go#28) and it indeed is running into the "not a hijacker" block again.

**Comment by systemfreund** [comment]
Here's how you can reproduce the problem:

* run `python -m http.server 1234`
* create file `upsteam.json`:
   ```
   { "service": { "name": "upstream", "port": 1234, "tags": ["urlprefix-/upstream"], "check": { "id": "upstream", 
   "http": "http://localhost:1234", "interval": "10s", "timeout": "1s" } } }
   ```
* run `consul agent -dev -config-file=upstream.json`
* run 
   ```
   fabio  -proxy.gzip.contenttype='^(text/.*|application/(javascript|json|hal+json|xml)|.*\+(json|xml))(;.*)$'
   ```
* run `nc localhost 9999 < failing-request`  (for contents of `failing-request` see previous comment)

**Comment by magiconair** [comment]
It was worth a shot. I'll add a proper test and fix it. I've got a long weekend ahead so this will probably happen next week - just to set expectations.

**Comment by magiconair** [comment]
Fixed it in the wrong place. The new patch should fix it.

Also, the websocket lib I'm using for testing doesn't make it easy to set headers. Therefore, writing a test requires a bit more work. I need to replace it anyway but I was able to reproduce the behavior with curl and the `--compressed` flag.

Could you have another look, please?

**Comment by systemfreund** [comment]
I can confirm now that the fix is working. Thank you very much!

**Comment by magiconair** [comment]
Cool. I'll write a test and merge it.
