### ISSUE TITLE
Q: Fabio installation and configuration without Docker

### ISSUE THREAD

**Issue by Rameshera** [fabiolb/fabio#303]
Hello,

I am planning to replace haproxy with fabio. When I run fabio binary and automatically register with consul and able to see all green consul UI. 

I am unable to find any docs without docker.

Currtly i am using consul, consul-template, nomad, haproxy and vault. I want to replace haproxy with fabio.

Can you please share any documention for the same.

Appreciate for your quick response.

Thnaks,
Ramesh

**Comment by magiconair** [comment]
Hi Ramesh, did you checkout https://github.com/fabiolb/fabio/wiki/Quickstart on the wiki?

**Comment by csawyerYumaed** [comment]
You have to download the binary, or build it yourself.  releases (tarball's and binaries) are available from the releases page:https://github.com/fabiolb/fabio/releases
