### ISSUE TITLE
X-Forwarded-Prefix header support

### ISSUE THREAD

**Issue by avarabyeu** [fabiolb/fabio#304]
While using fabio with urlprefix option, X-Forwarded-Prefix header is not passed to downstream requests. 
In this case downstream services are not able to generate correct back-links since they don't know their real path.

**Comment by magiconair** [comment]
How many of these headers are there? :)

What would it need to contain? The original request path?

**Comment by avarabyeu** [comment]
In my personal case i'd like to have the same behaviour that i had with Zuul :)
For example,
urlprefix-/myprefix opts strip=/myprefix
Since 'myprefix' is being stripped, X-Forwarded-Prefix=/myprefix should be added to be able to build valid request URL from upstream proxy. 
So yeah, it's original request path. But seems like only when you strip some part of it. 

btw, as far as i know, the following list are usually added:

- Forwarded
- X-Forwarded-Host
- X-Forwarded-Port
- X-Forwarded-Proto
- X-Forwarded-Prefix

Another important point is that you have to keep those headers from upstream proxy (if fabio itself  is placed behind proxy). In this case i should have two X-Forwarded-*** headers, one from upstream proxy and another one from fabio.

**Comment by magiconair** [comment]
@avarabyeu pushed a change with test. If you could verify that it works for you then I'll merge it and include it in the next release which I'll roll this week.

**Comment by avarabyeu** [comment]
@magiconair Just checked it. Seems like i didn't understand your question about original request path :) Header is added, but value should contain only the part that was truncated by proxy. 
For example:
We have registered service with the following params: urlprefix-/myprefix opts strip=/myprefix
I'm executing some GET: /myprefix/foo/bar
In current fix x-forwarded-prefix= /myprefix/foo/bar, but the correct value is just '/value'

btw, thanks a lot for prompt answers!

**Comment by magiconair** [comment]
`/value` or `/foo/bar` ?

**Comment by magiconair** [comment]
Ah, you want the stripped prefix to be in the header, e.g. `X-Forwarded-Prefix: /myprefix`

**Comment by magiconair** [comment]
@avarabyeu I've pushed an update to the branch. Can you check, please?

**Comment by avarabyeu** [comment]
@magiconair Checked. Works as expected! Thank you very much, looking forward for the release.
