### ISSUE TITLE
1.5.0 config compatibility problem 

### ISSUE THREAD

**Issue by pipozzz** [fabiolb/fabio#305]
Hello,

I have a problem with fabio upgrade to the latest 1.5.0

this is my config:
```
proxy.cs = cs=consul-cs;type=consul;cert=http://localhost:8500/v1/kv/ssl?token=token
proxy.addr = :443;cs=consul-cs,:80,:2375;proto=tcp+sni
```

I see in output just this:
2017/06/13 13:27:03 [FATAL] 1.5.0. =

Where could be a problem?

Thank you.

**Comment by magiconair** [comment]
I've refactored the code for parsing the `proxy.addr` values. Let me have a look.

**Comment by magiconair** [comment]
The problem is the second `=` in the `proxy.cs` line. This is a bug in the parseKVSlice code. I'll fix it.

**Comment by magiconair** [comment]
I've pushed a fix in the `issue-305` branch. Could you check whether this fixes the problem for you?

**Comment by pipozzz** [comment]
Great, I checked that, everything works properly, thanks

**Comment by pipozzz** [comment]
When do you plan to merge that fix to new release?
Thanks

**Comment by magiconair** [comment]
Today or tomorrow. Is that soon enough?

**Comment by pipozzz** [comment]
Great !!, I'm just asking

Thanks

**Comment by pipozzz** [comment]
Did you forget on this issue in new release?
I would like to use latest version of fabio, if possible.

**Comment by magiconair** [comment]
Damn. Yes. I'll push a 1.5.2 soon. Might be early next week though.

**Comment by pipozzz** [comment]
Thanks, it would help me a lot 👍
