### ISSUE TITLE
what is the tcp writeTimeout?

### ISSUE THREAD

**Issue by InformatiQ** [fabiolb/fabio#307]
could you clarify the wt and rt options?
and is there a way I could force fabio to close backend connections ?
Thank you

**Comment by magiconair** [comment]
`rt` and `wt` sets the read and write timeout on the inbound connection, the one accepted on the listening socket and handed off to the `TCPProxy`. The upstream connection does not have timeouts right now. This is a bit hidden here: https://github.com/fabiolb/fabio/blob/master/proxy/tcp/server.go

When you close the inbound connection the outbound connection should get closed as well if I read the code here correctly but maybe I need to brush up my TCP state knowledge.

https://github.com/fabiolb/fabio/blob/master/proxy/tcp/tcp_proxy.go

What is the problem you're having?

**Comment by InformatiQ** [comment]
we will be proxying carbon (graphite project) which opens up a connection and keeps it up, and we need to be able to balance the conn over the list of nodes.
The thing is it does not close the connection untill it is restarted. some sort of a health check on the upstream (such as CPU or queue size) would greatly help.

**Comment by magiconair** [comment]
@InformatiQ Is this still an issue?
