### ISSUE TITLE
/api/routes intermittently returns null.

### ISSUE THREAD

**Issue by spicykoala** [fabiolb/fabio#316]
I have a case where upon multiple hits of "/api/routes", null is intermittently returned. I noticed this because we have a task setup to poll this endpoint to check for route changes, and it was coming back true at odd intervals - turns out the request was returning null intermittently which was presented as a change.

(This is testable in the browser/postman)

**Comment by magiconair** [comment]
Since the routing table is atomically swapped I'd check the fabio logs if the routing table was temporarily empty. `null` shouldn't be able to happen (but I need to check the code to be certain)
