### ISSUE TITLE
Multiple urlprefix

### ISSUE THREAD

**Issue by jstoja** [fabiolb/fabio#317]
Hello,

Is there a reason why it's not possible to specify multiple urlprefix for a service?
We're trying to have services serving multiple REST ressources and I don't find how to implement this with fabio+registrator as shown in the documentation.
Looking at the code, it doesn't seem implemented.

**Comment by magiconair** [comment]
Just provide multiple tags.

**Comment by jstoja** [comment]
Indeed, already tried but the syntax wasn't good. Wasn't even linked to fabio!
For next people, you can specify multiple tags by splitting them with a comma:
`SERVICE_TAGS=urlprefix-/hello/ strip=hello, urlprefix-/world/`

**Comment by magiconair** [comment]
I'm glad you've figured it out. Let me know if there are other things. :)
