### ISSUE TITLE
http: proxy error: context canceled

### ISSUE THREAD

**Issue by tomstaijen** [fabiolb/fabio#318]
With the latest couple of version, we get a lot of these errors: 

fabio    | 2017/07/06 14:58:15 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled
fabio    | 2017/07/06 14:58:16 http: proxy error: context canceled

These are requests from visual studio polling a nuget server for updates by the way.
The complexe flow: 
visual studio -> fabio -> haproxy doing an url rewrite -> nexus repository manager.

We run fabio in a docker container.
We have these errors with any version later than 1.3.8-go1.7.5
With 1.3.8-go1.7.5, we don't have this problem. 
If I add a haproxy in front of fabio, I also don't get this error.
We're not using SSL.

Anyone got any idea if this can be caused by a go bug?

**Comment by tbouvet** [comment]
Same problem.
I try to add a route like : 

> route add new_service xx.domain.com http://a-new-url.zz.com

Fabio log : 
```
2017/09/27 14:21:34 http: proxy error: context canceled
2017/09/27 14:21:34 http: proxy error: context canceled
2017/09/27 14:21:34 http: proxy error: context canceled
```

**Comment by magiconair** [comment]
Can you post your runtime config?

**Comment by tbouvet** [comment]
```
+ service-a service.production.mydomain.com/ http://192.168.100.10:80/ 
+ new-service service.mydomain.com/ http://service.production.mydomain.com
````

**Comment by magiconair** [comment]
on which route is fabio causing the error? Is that reproducible? Do you have write or read timeout set in the config?

**Comment by tbouvet** [comment]
The error is when I test `http://service.mydomain.com` .
My simple config : 
```
proxy.addr = :9999,:443;proto=tcp+sni,:1234;proto=tcp
```

**Comment by magiconair** [comment]
Duplicate of #264

**Comment by magiconair** [comment]
Closing because of duplicate
