### ISSUE TITLE
access logging is not right

### ISSUE THREAD

**Issue by GeorgeYuen** [fabiolb/fabio#322]
LOG_ACCESS_FORMAT=fabio|$remote_host|$request_method|$response_time_ns|$response_status|$response_body_size|$request_uri

then i get 
fabio|192.168.193.7|GET|0.002534327|200|-1|/trading-service/api/v1/orders

response_body_size always -1

**Comment by magiconair** [comment]
Which version are you running?

**Comment by magiconair** [comment]
Also, can you please post a response from this endpoint. I'd need to see the headers. My guess is that there is no `Content-Length` header.

**Comment by GeorgeYuen** [comment]
I use docker magiconair/fabio:1.5.2-go1.8.3

register a spring boot project in fabio

2017-07-25 16:59:17:fabio|192.168.15.49|GET|0.002851322|200|-1|/doctor-kb/health

**Comment by GeorgeYuen** [comment]
result 

````
{
    "status": "UP",
    "diskSpace": {
        "status": "UP",
        "total": 482765783040,
        "free": 107016912896,
        "threshold": 10485760
    },
    "db": {
        "status": "UP",
        "database": "MySQL",
        "hello": 1
    }
}
````

````
Content-Length →155
Content-Type →application/vnd.spring-boot.actuator.v1+json;charset=UTF-8
Date →Tue, 25 Jul 2017 09:03:42 GMT
X-Application-Context →application:swagger:80

````

**Comment by GeorgeYuen** [comment]
yes the api don't have Content-Length header.
