### ISSUE TITLE
Send metrics to cloudwatch

### ISSUE THREAD

**Issue by discobean** [fabiolb/fabio#326]
It would be great to be able to have a plugin that sends metrics to AWS cloudwatch per endpoint

**Comment by magiconair** [comment]
The AWS Go client lib is a behemoth ...

**Comment by lforehan** [comment]
+1

**Comment by magiconair** [comment]
Please see https://github.com/fabiolb/fabio/issues/211#issuecomment-375880738

**Comment by magiconair** [comment]
If you want to help: now is the time :)
