### ISSUE TITLE
Possibility for Docker Image to pass Consul IP and Port as Variable?

### ISSUE THREAD

**Issue by multipathmaster** [fabiolb/fabio#346]
Would be awesome if the container that is built doesn't default to 127.0.0.1:8500, as within a larger environment, chances are, localhost 8500 is already bound on the consul agents as well as various things bound to nomad.  It would be rad if it could run like `docker run -it -e CONSUL_IP="IP" -e CONSUL_PORT="PORT" fabiolb/fabio` .  which then would allow user to specify the address themselves (i.e. what if it's load balanced behind a VIP and localhost doesn't cut the mustard?).

**Comment by magiconair** [comment]
`docker run -it -e registry_consul_addr=host:port fabiolb/fabio` should do the trick. Also, pls don't run consul behind an LB :)

**Comment by multipathmaster** [comment]
Magiconair, GRATSI AMIGO!!!!  -- MM

**Comment by multipathmaster** [comment]
I'm going to go ahead and close this issue, Magiconair, know you are a busy dude, thank you again for the information!

**Comment by magiconair** [comment]
no worries. Let me know if you have more questions
