### ISSUE TITLE
%20 in route is causing route mismatch,  regression in 1.5.2 , works with 1.3.7

### ISSUE THREAD

**Issue by devendram** [fabiolb/fabio#347]
our route with % in it used to work fine with 1.3.7 . After upgrading to 1.5.2 we are hitting issue with such routes . Please see following from fabio log

log
2017/09/08 12:44:17 [WARN] No route for localhost/run/before/test%201

route exists 
host	    localhost/run/before/test%201	http://127.0.0.1:22275/		100.00%

Tcpdump with fabio 1.3.7
=================

GET /run/before/test%201 HTTP/1.1
Host: localhost

HTTP/1.1 200 OK
Content-Length: 222
Content-Type: text/plain; charset=utf-8
Date: Fri, 08 Sep 2017 19:37:55 GMT
......

Tcpdump with fabio 1.5.2
===================

GET /run/before/test%201 HTTP/1.1
Host: localhost

HTTP/1.1 404 Not Found
Date: Fri, 08 Sep 2017 19:29:52 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

**Comment by magiconair** [comment]
Is the `%20` part of the route or the request?

```
rotue add svc /x/a%20b http://1.2.3.4:5678

or

rotue add svc /x http://1.2.3.4:5678

```

**Comment by magiconair** [comment]
Another difference is fabio 1.3.7 was built with go1.7.5 and fabio 1.5.2 is built with go1.8.3. Could be something in the go http package but I'm looking.

**Comment by magiconair** [comment]
nvm, I've found it. This is a consequence of #219 which uses `req.URL.Path` instead of `req.RequestURI` for the lookup. The first one is parsed whereas the other one isn't. Since you can encode a space in two ways in a URL (`%20` and `+`) I think the new way is the correct one but then the entries in the routing table need to be URL decoded. I need to think about this a bit. Is there something you need from 1.5.2 and this is a blocker?

**Comment by jshaw86** [comment]
@magiconair we upgraded to 1.5.2 for better TLS+SNI support which we need for one of our backend microservices(SOC Compliance).

**Comment by jshaw86** [comment]
@magiconair any idea on effort on this? We are trying to decide whether or not to invest our resources into this issue or not.

**Comment by magiconair** [comment]
How urgent is this since a) I'm sick right now and b) need to get something ready for HashiConf next week. Can this wait a couple of days?

**Comment by jshaw86** [comment]
@magiconair not urgent enough to warrant doing sick. I'll personally take a look at it in my free time and send a patch if I can solve it until you can get around to it. A few days is fine. Tell alex at hashi Jordan at PubNub says Hi. :)

**Comment by magiconair** [comment]
@jshaw86 will do :)

**Comment by jshaw86** [comment]
@magiconair have you had a chance to look at this? We're still looking at options outside fabio to work around this but still wanted your thoughts.

**Comment by magiconair** [comment]
consul 1.0 beta1 is out the door. I have one more thing to look at and then I'll dig into this one.
