### ISSUE TITLE
Case-insensitive path matching

### ISSUE THREAD

**Issue by jblackburn21** [fabiolb/fabio#35]
I have added this route to test with, but the path matching appears to be case-sensitive.

route add orders /orders http://localhost:8080/ tags "urlprefix-/orders"

A request to this url works correctly: http://localhost:9999/orders

However, a request to this URL: http://localhost:9999/Orders
logs this warning: [WARN] No route for localhost:9999/Orders

Is it possible for the path matching to be case-insensitive?  This would lessen the burden on the client to request the route with matching case.

**Comment by magiconair** [comment]
If I look at http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html section 3.2.3 I find this:

> 3.2.3 URI Comparison
> 
> When comparing two URIs to decide if they match or not, a client SHOULD use a case-sensitive octet-by-octet comparison of the entire URIs, with these exceptions:
> 
>       - A port that is empty or not given is equivalent to the default
>         port for that URI-reference;
>         - Comparisons of host names MUST be case-insensitive;
>         - Comparisons of scheme names MUST be case-insensitive;
>         - An empty abs_path is equivalent to an abs_path of "/".
> Characters other than those in the "reserved" and "unsafe" sets (see RFC 2396 [42]) are equivalent to their ""%" HEX HEX" encoding.
>

**Comment by magiconair** [comment]
You can just register both routes but my suggestion is to fix your app.

**Comment by jblackburn21** [comment]
Thanks for the quick response.  We are looking at using this with several ASP.NET Web API projects, which is case-insensitive.  However, I believe we can make adjustments for this to work.

**Comment by magiconair** [comment]
let me know how this works out.

**Comment by herbrandson** [comment]
This is actually preventing us from migrating to using Fabio. We have been using dcos/marathon-lb which allows for case insensitive urls. Because of this, switching to using Fabio would be a breaking change for us. It would awesome if perhaps we could do something like `urlprefix-SomeService strip=/SomeService ignoreCase=true`

**Comment by herbrandson** [comment]
After thinking about that request some more, I don't think we really care about ignoring case on a route-by-route basis. I think a command line switch to ignore case on all routes would be better (and I suspect significantly easier to implement in a performant way).

**Comment by magiconair** [comment]
@herbrandson I think adding another matcher in https://github.com/fabiolb/fabio/blob/master/route/matcher.go and adding a config option in https://github.com/fabiolb/fabio/blob/master/config/load.go#L250-L252 should do the trick. 

Feel free to send a PR.

**Comment by herbrandson** [comment]
I can't tell you how happy this makes me :)

I'll try to send a PR in the next couple of days.

**Comment by herbrandson** [comment]
PR sent: https://github.com/fabiolb/fabio/pull/553

**Comment by magiconair** [comment]
Merged #553
