### ISSUE TITLE
statsd - unable to parse line - gf metric

### ISSUE THREAD

**Issue by jaxim** [fabiolb/fabio#350]
Hi,

I am using v1.5.2 of the binary (fabio-1.5.2-go1.9-linux_amd64) I have configured fabio for statsd. I am getting the following message:

`statsd plugin: Unable to parse line: "my-test-host-0.fabio--requests.mean:0.00|gf"`

I noticed though that a commit has been done to change the metric from gf to g:
https://github.com/magiconair/go-metrics-statsd/commit/6f7a999fba713426930c960ab26f4bd888c414cc

**Comment by manos** [comment]
I started seeing this again too. Suspecting a regression.

**Comment by magiconair** [comment]
No, this is a different problem. I've fixed it but forgot to merge it :( The pubnub code has both changes now so I should go back to their impl. However, they also have tag support in it and some other changes. I'll do this separately. Lets fix this one first.
