### ISSUE TITLE
select color scheme from config to distinguish environments

### ISSUE THREAD

**Issue by reinoud** [fabiolb/fabio#359]
We run 3 different environments (prod, QA, test). All environments are configured almost identical. So the difference in the web ui between them is just a few characters in a long url.

Would it be possible to select a different color scheme CSS in the config, so the different instances would be visually different from a distance?

**Comment by magiconair** [comment]
@reinoud `ui.color` and `ui.title` should do the trick. We used this in our team for exactly that purpose:

https://github.com/fabiolb/fabio/blob/master/fabio.properties#L856-L868

**Comment by magiconair** [comment]
We used `red` (prod), `yellow` (test), `green` (dev)

**Comment by reinoud** [comment]
Thanks!

Reinoud

**Comment by magiconair** [comment]
:) closing
