### ISSUE TITLE
Documentation of the available metrics?

### ISSUE THREAD

**Issue by pvandervelde** [fabiolb/fabio#360]
Is there any documentation available that describes what the available metrics mean? I'm using statsd to gather metrics from fabio and I'm getting a whole bunch of metrics but I have no idea what they mean. Is there anywhere I can look to figure out what the values mean?

**Comment by magiconair** [comment]
I've just updated the wiki. Please let me know whether that is sufficient.

https://github.com/fabiolb/fabio/wiki/Features#metrics-support

**Comment by pvandervelde** [comment]
Looks good to me. The only additional question that comes up is what is the time unit for the timers? Is it milliseconds?
