### ISSUE TITLE
Support fabio.properties in Consul KV store

### ISSUE THREAD

**Issue by tbouvet** [fabiolb/fabio#365]
Is it possible to push the configuration file `Fabio.properties` directly in Consul KV store ?

The reason is to "not restart" Fabio if I want to update a parameter.

**Comment by magiconair** [comment]
I don't think that this is a good idea in general as it introduces a circular dependency between fabio and consul. How should fabio find the consul instance and the KV path? The main reason to use fabio is that you do not have to maintain its configuration all the time. Therefore, I'm curious what it is that you want to change at runtime.

**Comment by tbouvet** [comment]
@magiconair For example, I want to change log level.

**Comment by magiconair** [comment]
why? what's broken? our fabio instances weren't logging much (KBs/day). Simple log rotation was enough. Are you getting a lot of `Health changed` messages?

**Comment by tbouvet** [comment]
Yes too many health changed : 
```
2017/09/28 07:30:03 [INFO] consul: Health changed to #42680
2017/09/28 07:30:03 [INFO] consul: Health changed to #42683
2017/09/28 07:30:50 [INFO] consul: Health changed to #42690
2017/09/28 07:30:50 [INFO] consul: Health changed to #42693
2017/09/28 07:31:00 [INFO] consul: Health changed to #42696
2017/09/28 07:31:00 [INFO] consul: Health changed to #42698
2017/09/28 07:31:00 [INFO] consul: Health changed to #42699
2017/09/28 07:31:05 [INFO] consul: Health changed to #42701
2017/09/28 07:31:05 [INFO] consul: Health changed to #42703
2017/09/28 07:31:05 [INFO] consul: Health changed to #42704
2017/09/28 07:31:58 [INFO] consul: Health changed to #42713
2017/09/28 07:31:58 [INFO] consul: Health changed to #42716
2017/09/28 07:32:10 [INFO] consul: Health changed to #42718
2017/09/28 07:32:10 [INFO] consul: Health changed to #42721
2017/09/28 07:32:29 [INFO] consul: Health changed to #42726
2017/09/28 07:32:29 [INFO] consul: Health changed to #42729
2017/09/28 07:32:41 [INFO] consul: Health changed to #42730
2017/09/28 07:32:41 [INFO] consul: Health changed to #42733
```

So maybe a log level should be good (debug/info/warn)

**Comment by magiconair** [comment]
No, what you have there is either a flapping service or a service which has volatile data in its health check output (e.g. timestamp, pid, increasing number, ...) Each of these lines represents a write to the consul raft log which needs to be replicated and puts load onto your consul server cluster. Find the volatile data in the health check and fix it and you won't have that problem :)

**Comment by tbouvet** [comment]
ok thank you for your help 👍
