### ISSUE TITLE
[Question] Stats - Status code per service

### ISSUE THREAD

**Issue by krjensen** [fabiolb/fabio#371]
Hi,

I send all stats to a statsD instance, but im missing one nifty stat - http status code count per service.
You provide a global count of HTTP status codes, but I would like to e.g. see 404 for a given service.

**Comment by marcosnils** [comment]
Ping?. Any ideas?

**Comment by magiconair** [comment]
Yes, I'll pick that up with the metrics refactor.

**Comment by magiconair** [comment]
Please see https://github.com/fabiolb/fabio/issues/211#issuecomment-375880738

**Comment by magiconair** [comment]
@marcosnils Now is the time to provide input and help with #476
