### ISSUE TITLE
Wildcards in routing path

### ISSUE THREAD

**Issue by dansteen** [fabiolb/fabio#374]
Hi!  Thanks for all the work you've put into fabio.  It's a great product and I love the fact that it just works.   I did have one question.  Is it possible to use wildcards in route paths.   As an example:

```
/profile --> host_a
/assessments --> host_b
/profile/{profile_id}/assessments -> host_b
```
Where `{profile_id}` would be a wildcard in the actual route.  This would allow the "collections" pattern similar to what rails does.  Is something like this possible?

Thanks!

**Comment by magiconair** [comment]
Hi @dansteen, I'm glad you like it. It should get out of your way as much as possible.

I think the `glob` matcher should solve your problem. However, this is a global option.

https://github.com/fabiolb/fabio/blob/master/fabio.properties#L296-L303

Let me know whether that works for you.

**Comment by dansteen** [comment]
Nice! that looks like it should do it.  Thanks!

**Comment by magiconair** [comment]
I'll close this for now. Feel free to comment and I'll re-open if necessary.
