### ISSUE TITLE
host=www.mydomain.com not working

### ISSUE THREAD

**Issue by discobean** [fabiolb/fabio#375]
Hi,

If using `host=dst` it works as expected, but it looks like when specifying an override and using opts `host=www.mydomain.com` will not pass the host header as `www.mydomain.com`

Example override:
```
route add marz-test marz-test.domain.com/ http://52.15.183.149/ opts "host=916c80f7.ngrok.io"
```

The documentation here: https://github.com/fabiolb/fabio/wiki/Routing specifies that `host=domainname` can be used

**Comment by magiconair** [comment]
I'll have a look.

**Comment by magiconair** [comment]
@discobean I had the right instinct on #301. We would need to set this to something else. Looks like I was getting ahead of myself in the docs. Looks like this was an obvious thing. Could you test this?

**Comment by magiconair** [comment]
The only thing where I'm not sure are the requests where users want to set arbitrary headers on the request. However, this solves a problem now.

**Comment by discobean** [comment]
Yep, this patch is confirmed working now :)
