### ISSUE TITLE
make log compatible with the syslog protocol

### ISSUE THREAD

**Issue by RiRa12621** [fabiolb/fabio#397]
fabio currently is capable of logging to syslog if you tell it to but the problem with that is that it does not follow the regulations given in https://tools.ietf.org/html/rfc5424
therefore it is not possible to properly extract different severity levels from syslog with tools like rsyslog
the fix should be to use a library like https://github.com/hashicorp/go-syslog
and make a switch in the logger that will result in an extra option 
if syslog 
then use this library and log according to the RFC

**Comment by magiconair** [comment]
Good to know. I'll have a look.

**Comment by RiRa12621** [comment]
i put a ticket on our internal board to get some time for this so that either @sielaq or me can work on this an bring a pull request

**Comment by magiconair** [comment]
@RiRa12621 That would be even better :)

**Comment by RiRa12621** [comment]
since i'm not at eCG anymore, I think no one keeps track of this. Can be closed
