### ISSUE TITLE
Fabio for task/container/service load balancing on amazon ecs with consul and registrator. 

### ISSUE THREAD

**Issue by ethicalmohit** [fabiolb/fabio#402]
Hey Guys,

Help needed to set up Fabio for load balancing of services on Amazon ECS. 
I have set up Amazon ECS cluster with Consul - For service discovery and Registrator - To register/de-register the tasks to the consul server. I am able to discover service using DNS/HTTP and I am getting different IP/Ports(Dynamic Host Port). I need to setup Fabio to balance the load above those tasks/containers of one particular service and I can use only the service name In my application by which they can connect to each other. 

Is there the automated way by which Fabio can handle load balance amongst each service with dynamic host ports and give any IP underneath with associated port to connect?

**Comment by magiconair** [comment]
From first reading I'd say that is exactly what fabio does. You register services in consul with their `host:port` and a `urlprefix-` tag which announces the `/path` (http) it can handle or the public `:port` (tcp) it should be contacted on and fabio does the load balancing. Somehow I think I'm missing something here. 

Can you try to explain it in a different way?

**Comment by ethicalmohit** [comment]
Thanks Frank for your reply. 
Right now, I have not registering service to the consul. Registrator is does that automatically. As you run the registrator on Amazon ECS cluster, It picks up the task running in there and add them up in consul. Is there any other way to do that? Or Anyway to ask regiatrator to append tags while registering services?

**Comment by magiconair** [comment]
registrator has a command line option which allows you to add tags.

http://gliderlabs.github.io/registrator/latest/user/run/

**Comment by ethicalmohit** [comment]
@magiconair Hey, Thanks, man. Is there any way to pass the -tag parameter with the docker run?

**Comment by magiconair** [comment]
Not that I know of since Docker does not handle the service registration. That’s what the registrator does. I could write a small app myself which does the same thing.

**Comment by leprechau** [comment]
Registrator will read environment variables from the container to set the service name, port and tags sent to consul.  You can put those in a docker-compose file, in the actual Dockerfile, or via docker cli with the -e switch.

**Comment by leprechau** [comment]
See here for the general service options look here under metadata and examples:

https://gliderlabs.com/registrator/user/services/

Heath checks (you will need one) here under the consul backend:

https://gliderlabs.com/registrator/user/backends/

**Comment by ethicalmohit** [comment]
@leprechau It just needs a -tag parameter while running the registrator, as mentioned by @magiconair . I will just run the docker command as mentioned in the registrator docs. I am not creating the docker file for registrator. Do you want me to create a Dockerfile with the "-tag" parameter? 

Docker run command for registrator:

```
docker run -d \
    --name=registrator \
    --net=host \
    --volume=/var/run/docker.sock:/tmp/docker.sock \
    gliderlabs/registrator:latest \
      consul://localhost:8500
```

**Comment by leprechau** [comment]
You need consul to register the service with the ‘urlprefix-‘ tag and setup a health check for the service before fabio will publish it.  To do that via registrator only using ‘docker’ without a modified Dockerfile or a compose file you will need to pass the various ‘SERVICE_’  environment variables to define the service entry and health check.  This is exactly what we do with our non-consul aware frontend containers.

**Comment by leprechau** [comment]
You don’t need to pass anything to the registrator run command ... you need to pass environment settings to the containers you want registrator to handle.

**Comment by leprechau** [comment]
The `-tags` option to registrator itself is global.  It doesn't make much sense to set the exact same `urlprefix-` tag on every service.  You want that tag to be reflect the actual path and/or port of each service so it should be set per container.  That is why you want to use the environment variables and the various `SERVICE_` options such as `SERVICE_NAME` and `SERVICE_TAGS`.

**Comment by leprechau** [comment]
@magiconair Seems like this question has come up before.  Would you like a PR with some documentation around fabio+registrator in the wiki?  Possibly under the `Service Configuration` section?

**Comment by magiconair** [comment]
@leprechau That would be great. I think you can just edit the wiki yourself.

**Comment by leprechau** [comment]
Okay, I'll give it a go.

**Comment by leprechau** [comment]
You already have a full example there for registrator.  I just didn't see that before.

**Comment by magiconair** [comment]
I forgot about that as well. Someone else provided that to me. Maybe add a link to a more prominent place?

**Comment by leprechau** [comment]
Could just link the registrator information into the side menu?

**Comment by magiconair** [comment]
I've added also a link to the Docker compose example to the side menu.

**Comment by magiconair** [comment]
@leprechau thx for adding the link.
@ethicalmohit do you have all the info you need?

**Comment by ethicalmohit** [comment]
@magiconair Thanks a lot.
