### ISSUE TITLE
configure equivalent  of nginx client_max_body_size

### ISSUE THREAD

**Issue by johnjolet** [fabiolb/fabio#422]
We are moving a service from behind nginx proxies to containers behind fabio.  we currently, for some locations, override the default client_max_body_size, and i can't find any reference for what that sort of limit is in fabio, or how i'd override it.  I may need to set it as high as 12M (i'd prefer to do that on a per-route basis, but would be willing to do it on a per-listener basis, like the rt and wt options).  what is the current limit and is there any way to increase it, if that limit is less than 12M?

**Comment by magiconair** [comment]
I don't think there is a limit and if you need a limit I would have to add that. The simplest thing is to add a global option but I think a per-route parameter is also not more difficult. Is not having a limit a blocker for you using fabio at all?

**Comment by johnjolet** [comment]
no, not having a limit is not a blocker.  having a limit i can't modify would be.  Thanks!
