### ISSUE TITLE
Fabio does not remove service when one of the registered health-checks fail

### ISSUE THREAD

**Issue by systemfreund** [fabiolb/fabio#427]
Given a service that has two health-checks and one of them is failing, fabio still considers that service to be healthy. According to https://github.com/fabiolb/fabio/blob/master/registry/consul/passing.go this behaviour is intended and not a bug. 

My question would be if this behaviour is really intended, or maybe is the implementation just a too simplistic one that could be improved?

**Comment by magiconair** [comment]
I don't know. What would you expect to happen?

**Comment by systemfreund** [comment]
In my particular case I'd expect fabio to remove the route. I am not saying that the current implementation is wrong, neither would my particular expectation be general enough for all use-cases.

Making it configurable would perhaps be the best option:
* All health checks must pass (my use-case)
* At least one health-check must pass (current behaviour)

I can live with the current limitation and remove the secondary health-check from my service. Anyways, would an option to configure the behaviour desirable?

**Comment by magiconair** [comment]
I can’t decide on what’s right for every setup so this should be configurable then. You want to send a PR?

**Comment by slackpad** [comment]
Consul internally for deciding whether to return an instance in a DNS query will AND all the service-level check statuses as well as the node-level ones, so if any are failing it is taken out of service.

**Comment by magiconair** [comment]
@slackpad Thanks. That's good to know. In that case fabio should behave like Consul. Adding the setting and switching to 'strict' in a later release seems like the right approach.
