### ISSUE TITLE
Wildcard registeration issues

### ISSUE THREAD

**Issue by shay-stratoscale** [fabiolb/fabio#440]
Hey,

We've been using fabio for a while now, and recently we've migrated part of a service functionality to another.
In order to switch the between the backend seamlessly we'd like to register some of the old endpoint to the new service (the other endpoint should keep on routing to the old one).

The old service is registered like so:

`urlprefix-/service/foo`

I would like to migrate an endpoint of the following format to the new service

`/service/foo/{some-id}/bar`

I tried using a wildcard like so:

`urlprefix-/service/foo/*/bar`

but it didn't seem to work.

I'm wondering if I'm doing something wrong or maybe this is not supported.
(I'm using consul tags for the registration)

Thanks,
Shay

**Comment by magiconair** [comment]
You can use the glob matcher to achieve this. I've noticed that the documentation for this is a bit bare-bones and updated it on the website:

http://fabiolb.net/ref/proxy.matcher/

**Comment by magiconair** [comment]
Once you enable the glob matcher your `urlprefix-/service/foo/*/bar` should work. Please let me know if it doesn't.

**Comment by shay-stratoscale** [comment]
Indeed it worked once I configured the `glob` matcher.

Thanks for your help @magiconair!
