### ISSUE TITLE
route add ... opts "proto=tcp+sni" ??

### ISSUE THREAD

**Issue by taemon1337** [fabiolb/fabio#444]
I cannot find an example of how to use the route add to add an SNI route, I checked the route_test.go and the docs but couldn't find it.

`
route add test-sni-route foo.bar.com foo.bar.cluster.local weight 1 opts "proto=tcp+sni"
`

This was my best guess but fails with invalid route.

p.s. This is for the Kubernetes backend I'm working on.

**Comment by taemon1337** [comment]
Nevermind, that did seem to work, I just needed double quotes for opts, not single, sorry

**Comment by magiconair** [comment]
@taemon1337 if the documentation could be improved then please let me know where you looked and couldn't find the info or a good example.

**Comment by taemon1337** [comment]
I looked at the examples in 'route/parse_test.go' as well as the 'Config Language' section on the site and couldn't find any example with tcp+sni, it was pretty obvious and I got it myself, mostly just my newness with go I think, but you could always add the above to parse_test.go if you wanted.

Btw, I'm testing my Kubernetes backend shortly

**Comment by magiconair** [comment]
Looking forward to it. Maybe time to add the UDP+SNI support ...

**Comment by taemon1337** [comment]
Crap!  So I can compile fabio just fine and I can build it using the provided Dockerfile, but it does not execute inside that container, it always says:
`
standard_init_linux.go:187: exec user process caused "no such file or directory"
`

you ever seen this before?  Do I need to use the 'Makefile' to build the container or something?

**Comment by leprechau** [comment]
@taemon1337 Usually that's due to using an image that doesn't have `/bin/bash` such as a scratch or Alpine Linux container.  The default `entrypoint` being `/bin/bash` causes that problem.  More generally it's because whatever you have specified as your `entrypoint` doesn't exist inside the container.

**Comment by taemon1337** [comment]
http://blog.xebia.com/create-the-smallest-possible-docker-container/

**Comment by magiconair** [comment]
Hmm, is this because of `os.Getuid()`? This works in the container I've built but I'm using `CGO_ENABLED=0`. Just tried `docker run -it fabiolb/fabio:1.5.7-go1.9.2` but I didn't try that before.

**Comment by magiconair** [comment]
Interesting. I thought I was using `CGO_ENABLED=0` but I'm not ...

**Comment by magiconair** [comment]
Ah, the `.goreleaser.yml` uses that. Blessing of multiple build systems...

**Comment by taemon1337** [comment]
Sweet!  That blog post got it.  I compiled like this:
`
docker run --rm -e CGO_ENABLED=0 -v $(pwd):/go/src -w /go/src golang:1.9.3 go build -a -ldflags '-s' github.com/fabiolb/fabio
`

The CGO_ENABLED=0 forced Go to compile all deps (not cgo) and the ldflags reduced the image size to 7.5M
