### ISSUE TITLE
TCP Proxying SSH connections

### ISSUE THREAD

**Issue by far-blue** [fabiolb/fabio#445]
Has anyone worked out how to get SSH connections to work via the TCP Proxy facility?

**Comment by magiconair** [comment]
What’s the problem?

—
Frank Schröder

**Comment by far-blue** [comment]
I get `ssh_exchange_identification: Connection closed by remote host`

There's no real debug info available. My suspicion is that the handshake is failing because the IP address of the client doesn't match the IP address of the proxied connection - or the same in revers for the server.

I don't think the problem is one Fabio can fix but I wondered if anyone else had worked out how to configure the ssh server and client so they don't get upset.

**Comment by magiconair** [comment]
Interesting. Please share a solution if you find one. 

—
Frank Schröder

**Comment by far-blue** [comment]
I worked it out and it wasn't an ssh issue after all :) I use Nomad and Bitbucket Server and had created 1 service with 2 tags - one for http and one for the tcp proxying. Nomad had created the service in a way that resulted in both the http proxy *and* the tcp proxy routing to the container's http port 8080.

The solution was to split the config into 2 services, each with a specific port number in the nomad config.
