### ISSUE TITLE
'-registry.consul.register.enabled' does not seem to be respected

### ISSUE THREAD

**Issue by jrasell** [fabiolb/fabio#467]
I wish to disable the default Fabio registration in Consul in order to use my own health checks and from its description am trying to use the `-registry.consul.register.enabled` flag to do this. Within my Nomad job specification file I am supplying the flag:

```
args = [ "-registry.consul.register.enabled", "false"]
```

When submitting the job however, Fabio is configured with `"Register": true,` which is also reflected through the Consul UI which shows the service check `Service 'fabio' check service:fabio-*` registered.

Additional config:
```
"Addr": "localhost:8500",
            "Scheme": "https",
            "Token": "",
            "KVPath": "/fabio/config",
            "NoRouteHTMLPath": "/fabio/noroute.html",
            "TagPrefix": "urlprefix-",
            "Register": true,
```

**Comment by magiconair** [comment]
Try 

registry.consul.register.enabled=false

—
Frank Schröder

**Comment by jrasell** [comment]
@magiconair thanks a lot, that does sort it. Thanks also for the project, I am a big fan of it!
