### ISSUE TITLE
Add support for Vault 0.10 KV v2

### ISSUE THREAD

**Issue by danlsgiga** [fabiolb/fabio#483]
Since Vault 0.10 introduced the secret backend KV v2, the data structure and API endpoints to retrieve certificates has also changed. For now we are keeping our certificates mountpoint on v1 but it would be great to have Fabio supporting KV v2 as well.

**Comment by magiconair** [comment]
Can you provide a PR?

**Comment by pschultz** [comment]
@danlsgiga, judging from the patch in #497, it looks like all you have to do to use the V2 backend is to update your Fabio config from

    cs=<name>;type=vault;cert=secret/fabio/certs

to

    cs=<name>;type=vault;cert=secret/data/fabio/certs

There doesn't seem to be a change required in Fabio itself.

**Comment by danlsgiga** [comment]
Hi @pschultz, yeah, before submitting the issue I've tried Fabio with the newer path structure used in v2 but it didn't work. Thanks for looking into it though!

**Comment by pschultz** [comment]
This is addressed by !497 and can be closed now.

**Comment by leprechau** [comment]
@pschultz Got it, thank you!
