### ISSUE TITLE
Fabio decodes URL path parameters

### ISSUE THREAD

**Issue by mcneiljt** [fabiolb/fabio#486]
Related issue/change:
https://github.com/fabiolb/fabio/issues/347
https://github.com/fabiolb/fabio/commit/cc3e3cd601abbb48a6f0d152a45c9c013b78b399

While using fabio a team mate noticed that some of our URL path parameters, such as resource Ids, which have url-encoded content in them are being decoded by fabio causing 404 errors. The decoded path parameters are sent to the service and not recognized as a valid path.

Example:
container/job with `urlprefix-/posts`
request: GET /posts/abcder%2Fsdf394/comments

This matches the URL prefix, but routes to `/posts/abcder/sdf394/comments` which isn't a valid path and thus returns a 404.

**Comment by tuempeltaucher** [comment]
Any chance to see a fix here? We have the same problem with https://domain.tld as a path param.

**Comment by leprechau** [comment]
There is work and discussion going on in #489 ... would you be able to test if that patch fixes your issue?

**Comment by tuempeltaucher** [comment]
No, that didn't change anything.

[TRACE] abc Tracing xxx/stella/v1/xzy/https://wwwi.screenwork.de/
[...]
[TRACE] abc Routing to service stella on http://10.0.1.4:25853/
"GET /stella/v1/xyz/https%3A%2F%2Fwww.screenwork.de%2F HTTP/1.1" 404 43 "" "curl/7.29.0" http://10.0.1.4:25853/v1/xyz/https://www.screenwork.de/

But I traced it done and added a few "RawPath"s:

https://github.com/tuempeltaucher/fabio/commit/a06f98503d063e88b123176296f79a03bf0bf3ea

**Comment by leprechau** [comment]
@tuempeltaucher that's with the code from #489 applied?

**Comment by tuempeltaucher** [comment]
Yes, I forked valentin-krasontovitsch:url_decoding_in_routing, that is the branch from his pull request.

**Comment by tuempeltaucher** [comment]
Any news here?
