### ISSUE TITLE
Fabio confi help with multiple proto

### ISSUE THREAD

**Issue by satishviswanathan** [fabiolb/fabio#490]
My consul services is having multiple services with different protocols, some use http and other tcp.  Now I'm trying to populate the fabio routing table with all these services with the following command.

The issue is my http services are not available since fabio is being exposed as a TCP proxy at port 2302.

fabio-1.5.8-go1.10-windows_amd64.exe -registry.consul.addr 10.XXX.XXX.XX:8500 -proxy.addr :2302;proto=tcp, :/;proto=http

**Comment by satishviswanathan** [comment]
@magiconair Do you think it is possible to expose my TCP services at 2303 and HTTP services at 9999.

Fabio Routing table 
![fabio-multiple-proto](https://user-images.githubusercontent.com/17437409/40192981-828b842c-59cb-11e8-95ee-afcccdea9ec6.png)

**Comment by shibukraj** [comment]
Is this can be done in Fabio? Or do we need to configure separate fabio instances per Protocol?

**Comment by leprechau** [comment]
If you need a TCP listener and also an HTTP listener to enable the HTTP features you will need to define multiple listeners on different ports and/or different IPs.

Example from our lab configuration:
```
proxy.addr = 172.27.18.68:80;proto=http;rt=60s;wt=30s,\
             172.27.18.68:443;proto=https;rt=60s;wt=30s;cs=all;tlsmin=10, \
             172.27.18.68:8443;proto=tcp+sni
```

This binds to `172.27.18.68` on three different ports `80`, `443`, and `8443` using three different protocols for each listener.

**Comment by shibukraj** [comment]
Thanks that worked perfectly. What I have seen is we need to define TCP first and then HTTP. 
Thanks again.

**Comment by zpeterg** [comment]
Thanks, @leprechau , I looked for some time for how to chain protocols. The documentation seems to omit this.

**Comment by leprechau** [comment]
Np, I'll see about adding a more complete example to the documentation.

**Comment by jarrettj** [comment]
Agreed, adding a couple of examples would be awesome! :)

**Comment by leprechau** [comment]
Sorry, I forgot about this ... I'll add to the docs today.

**Comment by leprechau** [comment]
Better late than never I guess.  Sorry for the delay.

**Comment by jarrettj** [comment]
No worries :)
