### ISSUE TITLE
Question: wildcard hostname support

### ISSUE THREAD

**Issue by far-blue** [fabiolb/fabio#491]
Hi all :)

Just a quick question. I know path matching is longest path but what's the behaviour on hostname?

I currently have a couple of machines that host staging builds which are named by project and build number and they have dns setup with a wildcard (*.example.com style). Having separate dns for these is a shame and it would be nice to move them behind Fabio.

Can Fabio be setup with the following behaviour?:

*.example.com -> [known IP address]

So, for instance:
www-1234.example.com -> [known IP address]
foo-356.example.com -> [known IP address]

etc.

**Comment by magiconair** [comment]
Yes.

**Comment by far-blue** [comment]
ah, great :D I guess it's `url-prefix-*.example.com/`

**Comment by magiconair** [comment]
That should work. Let me know if it doesn’t.

—
Frank Schröder

**Comment by far-blue** [comment]
\o/ yes, that works fine :)

Thanks :)

**Comment by joshuaclausen** [comment]
I realize this is a closed issue, but I figured I'd ask about wildcards in other places in a hostname:

services-live*.example.com
*services-*-north-america*.example.com

I tried briefly with services-live*.example.com, but it didn't seem to work, so it seemed worth asking on the subject.
