### ISSUE TITLE
Tls + sni support for non http traffic? 

### ISSUE THREAD

**Issue by ashish235** [fabiolb/fabio#499]
Hi guys,

Is it possible to have sni feature for normal tcp traffic possibly for grpc. Which is not a http type traffic.

Sorry. if that is not feasible at all. Total noob with SNI stuff.

**Comment by leprechau** [comment]
There is a tcp+sni listener that should work for that case.  We are using it for services that terminate TLS directly and enforce client certificate authentication.  Look at the `proto=tcp+sni` option on the `proxy.addr` setting.

**Comment by ashish235** [comment]
@leprechau , thanks will give it a try.
