### ISSUE TITLE
UI broken where no internet access.

### ISSUE THREAD

**Issue by yakcamnevets** [fabiolb/fabio#502]
Hello, the UI is broken on computers where to there no internet access. Could the jquery, materialize, etc. resources be included in fabio instead of loaded from the internet? Thanks.

Loading failed for the <script> with source “https://code.jquery.com/jquery-3.3.1.min.js”.
routes:7
Loading failed for the <script> with source “https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js”.
routes:10
ReferenceError: $ is not defined[Learn More]

**Comment by gnoymmij** [comment]
2nd that. any work around or the intention to fix this?

**Comment by magiconair** [comment]
Feel free to send a PR. This shouldn't be hard to fix.
