### ISSUE TITLE
Headers passed through fabio are modified

### ISSUE THREAD

**Issue by kuskmen** [fabiolb/fabio#505]
Hi guys, 
I noticed that sending headers to fabio modifies the header key, for instance header with key `claim-siteid` when passed to fabio and then to the service it arrives as `Claim-SiteId`. Tbh I am not sure if this is desired behavior or it is made so because of good practices, but I wanted to verify it with you.

**Comment by magiconair** [comment]
This is a side-effect of http header normalization within the Go http library. HTTP header names are case-insensitive.
