### ISSUE TITLE
Would it be possible to configure Fabio to watch services with warning state?

### ISSUE THREAD

**Issue by kuskmen** [fabiolb/fabio#509]
Hi guys,
I am currently looking for a nice way of implementing our API health check status decision. 

Consider this scenario - I have a service which depends on multiple other services in order to provide multiple functionalities. For the sake of argument lets say that there is logical mapping between my dependent services and functionalities my service provide.  This means that in order to provide functionality(we will call it *F*) some dependent service must be healthy(we will call it *S*). With that being said couple of scenarios emerge:
* My service calls service *S* and other dependent services and responses are that they are healthy - No problems here my service is also healthy than.
* My service calls service *S*, it is critical, but then all other services completely unrelated to functionality *F* I provide are healthy. - Now I have a decision to make is my service healthy or not but this decision is though, because why should I consider my service as critical if all other functionalities besides *F* I can easily provide. And vice verse, I should not consider my service healthy because I am not able to provide 100% of the functionalities it usually provides.
* My service calls service *S*, it is healthy, but then one or more services completely unrelated to functionality *F* I provide are not healthy. - This is basically the same as the second bullet.
* My service calls service *S* and all other dependent services and they are not healthy - No problem again I shall consider my service as not healthy as well.

According to Consul documentation, it provides three statuses in the response of /health - (2xx - healthy, 429 - warning, everything else - critical). You can see how warning status can fit here really good into the scenario. All this have unfortunate problem however https://github.com/fabiolb/fabio#getting-started 

> Make sure the health check is passing since fabio will only watch services which have a passing health check.

 although I do not have enough knowledge of Fabio, hence asking you guys, if there is any way to configure Fabio to watch for services that are in warning state as well and does all of this makes sense to you?

Sorry for the long post. Here is potato: :potato:

**Comment by magiconair** [comment]
I think what you are looking for is https://fabiolb.net/ref/registry.consul.service.status/

**Comment by kuskmen** [comment]
Hmm thanks mate it looks like it is indeed, but shouldnt we change the getting started page then?
