### ISSUE TITLE
Logging fabio-output to log file

### ISSUE THREAD

**Issue by Roseidon** [fabiolb/fabio#514]
Hi guys,

is there a possibility to write the console output from fabio to a log file?
The only way I found so far was logging the access  to stdout, but not a file.

**Comment by magiconair** [comment]
No. This should be handled by your supervisor which does the log file redirection. 

—
Frank Schröder

**Comment by leprechau** [comment]
@Roseidon how are you running fabio today?

**Comment by leprechau** [comment]
Closing due to lack of response.  Future users - your system should be more than capable of taking the stdout of fabio and writing it to a system log.  Check the systemd/docker/upstart documentation for more information.
