### ISSUE TITLE
Fabio - Manual overrides

### ISSUE THREAD

**Issue by satishviswanathan** [fabiolb/fabio#515]
How do we enable Manual overrides in Web UI?

Can someone share the steps for enabling this feature.

**Comment by ggerritsen** [comment]
You can put configuration for manual overrides in the web ui (https://fabiolb.net/feature/web-ui/). 
See e.g. https://fabiolb.net/cfg/#route-add for how to add a route.

**Comment by leprechau** [comment]
You should click on 'Overrides' and see a dropdown like ...

<img width="375" alt="screen shot 2018-06-29 at 3 17 04 pm" src="https://user-images.githubusercontent.com/1444686/42113032-873686b0-7baf-11e8-90d9-94235df266c3.png">

Once you click on 'default' there you should be taken to the manual routes section ...

<img width="1338" alt="screen shot 2018-06-29 at 3 16 35 pm" src="https://user-images.githubusercontent.com/1444686/42113051-9e6295cc-7baf-11e8-8317-b5a1ba8158a9.png">

In this case I have exactly one manual route entered.  That route is contained within the consul kv store and in my case is located at `/lb/fabio/config` per the `registry.consul.kvpath` setting.  The default is `/fabio/config`.

If I look at that key in consul I see the same content as the screenshot above ...

<img width="1123" alt="screen shot 2018-06-29 at 3 20 40 pm" src="https://user-images.githubusercontent.com/1444686/42113189-049f6324-7bb0-11e8-963c-303ebc90dd91.png">

I hope that helps.

**Comment by leprechau** [comment]
The `ui.access` settings needs to be `rw` which is the default.

**Comment by satishviswanathan** [comment]
Thank you that worked !

Using the command I was able to add a new route. This routes needs to be in the consul kv but I'm not able to see that in the kv store.

**Comment by leprechau** [comment]
Good, closing this issue.  Feel free to re-open if it's not actually resolved.
