### ISSUE TITLE
How can I configure fabio with single public IP load balanced to 3 nodes with private IPs

### ISSUE THREAD

**Issue by sreejithdivakar** [fabiolb/fabio#516]
Hi,

I am trying to setup a 3 node consul webcluster with the design as shown below. Fabio is running in all the three nodes and adding routes to all . All three nodes are also installed with consul and running in server mode. 

![image](https://user-images.githubusercontent.com/30250155/42078573-5e0e14ae-7bc0-11e8-939e-030256291409.png)
![image](https://user-images.githubusercontent.com/30250155/42078764-0e356b98-7bc1-11e8-8863-e023d106a075.png)

```
           +------ HTTP/HTTPS -> fabio -+- HTTP -> service-a (host-a)
           |                       |
internet --+---HTTP/HTTPS -> fabio -+- HTTP -> service-b (host-b)
           |                       |
           +-------HTTP/HTTPS -> fabio -+- HTTP -> service-c (host-c)
```

![image](https://user-images.githubusercontent.com/30250155/42078945-991e90fe-7bc1-11e8-8bf3-5f87e844b9c0.png)

I need to use Fabio as a load balancer so that HTTP request to a "SINGLE PUBLIC IP" should be load balanced to (hosta) / (hostb) / (hostc) with private IPs. How should I configure fabio to achieve this scenario?

Thanks in advance
Sreejith

**Comment by leprechau** [comment]
What you are asking is actually outside the scope of fabio and most other load balancers.  It sounds like you want a single public facing virtual IP (VIP) to be load balanced across multiple service instances.

That's a job usually reserved for the network layer.  In our case we use Anycast BGP to accomplish this task.  https://en.wikipedia.org/wiki/Anycast

**Comment by sreejithdivakar** [comment]
Hi leprechau...
Thanks for your response....really sorry for the late response.
Regards
Sreejith
