### ISSUE TITLE
Redirection to default back-end if route not exists

### ISSUE THREAD

**Issue by andreyshamray** [fabiolb/fabio#521]
Hi, guys. Sorry, if this functionality already exists but for some reason, I can't find it(. 
So, basically we need to - if no route is matched in the routing table, Fabio should route to a "default" backend. And "default" backend, in this case, will be another Fabio URL which is connected with separate Consul dc. Will be very grateful if you can help with this.

Thanks in advance!

**Comment by leprechau** [comment]
That's currently handled by a `/` route.  You could make that a static route or an advertised service with a `urlprefix-/` tag.

**Comment by andreyshamray** [comment]
Hi, thanks for fast response. I will try to implement this approach today.

**Comment by andreyshamray** [comment]
Hm strange, but routing is not working for me. Could you pls give an advice on this.
1. I have added config like this:
``` cat fabio.properties 
registry.static.routes = \
    route add / / http://rpc-fabio.kube.com:9999/```
2.  Now I am starting Fabio:
``` ./fabio -cfg fabio.properties```
3. Hit in browser something like this:
```my-fabio.com:9999/my-service``` and it give's me 404, but I am expecting to be redirected to ```rpc-fabio.kube.com:9999/my-svc```
4. And does Fabio support route configuration threw env variables, like FABIO_REGISTRY_CONSUL_ADDR?

**Comment by andreyshamray** [comment]
Hi, guys. Did you have a chance to take a look at my previous comment?
Thanks a lot.

**Comment by andreyshamray** [comment]
So finally we have configured it, the problem was with the host header.
```
route add product-svc / http://rpc-fabio.kube.com/ opts "host=dst"
```
And does Fabio support route configuration threw env variables, like FABIO_REGISTRY_CONSUL_ADDR?

**Comment by leprechau** [comment]
Awesome, glad  you got it figured out.

>And does Fabio support route configuration threw env variables, like >FABIO_REGISTRY_CONSUL_ADDR?

No, the route/registry backends are static (in config), file (reloadable), and and consul currently.

**Comment by andreyshamray** [comment]
Ok, thanks a lot!) I think I will use put method to just add the desired route to consul KV)
