### ISSUE TITLE
Problem geting fabio routing to its own ui

### ISSUE THREAD

**Issue by nkissebe** [fabiolb/fabio#525]
Maybe what I want to do is strange, but....

I am running fabio in a docker container with FABIO_REGISTRY_CONSUL_REGISTER_TAGS = "urlprefix-mydomain.org/fabio" and FABIO_REGISTRY_CONSUL_REGISTER_ADDR set to the fabio ui address.

It routes correctly but then the fabio ui redirects to mydomain.org/routes. It loses the "fabio" path segment. I tried different strip options with no effect. I think fabio ui needs a variable telling what its base url is. If I use a urlprefix of "fabio.mydomain.org/" it works just fine.

I was hoping to get all the hashicorp web uis to appear as mydomain.org/fabio, mydomain.org/consul, mydomain.org/nomad, mydomain/vault.  I haven't tried the others but I expect they will have similar problems so this issue may be moot.

Is it just not possible?

**Comment by nkissebe** [comment]
I no longer care about this issue. Can't do this with other hashicorp tools anyway so wouldn't matter to me if fabio could do this or not.

**Comment by leprechau** [comment]
Sorry for the late response ... but you could probably do all of this through fabio.

You could register Nomad with a `urlprefix-/nomad/ strip=/nomad` and do the same with Consul and Vault and others.   In theory that should work.  Assuming you had `mydomain.org` pointing to an instance of fabio.
