### ISSUE TITLE
urlprefix- does not work properly

### ISSUE THREAD

**Issue by jorjika** [fabiolb/fabio#527]
Hello. I have simple setup of Consul and fabio. I've registered service in consul with tag urlprefix-/service1.
Fabio added route correctly. When i query  http://{myfabiourl}:9999/service1/api or http://{myfabiourl}:9999/service1/swagger/index.html (my service is written on .net core and it has some subdirectories) it does not work. It shows only result for http://{myfabiourl}:9999/service1.

I've read documentations and did not find anything that could help me in this situation.
 Is this an issue or am i missing something?

**Comment by satishviswanathan** [comment]
What is the error that you are getting?

You have mentioned service1 as the urlprefix and your actual end point url might not be having service hence you might require to do strip that prefix.

While registering the consul service you can define the urlprefix and strip it as shown below.

Ex:
 "Tags": ["urlprefix-/service1 strip=/service1"]

**Comment by jorjika** [comment]
@satishviswanathan  thanks. I needed "strip" option. It worked well :)

**Comment by satishviswanathan** [comment]
Glad to hear it worked for you !
