### ISSUE TITLE
Port range in the proxy.addr

### ISSUE THREAD

**Issue by shantanugadgil** [fabiolb/fabio#529]
Can Fabio do a range of ports in the `proxy.addr` syntax?

I wan't able to deduce if it is possible from here:
http://fabiolb.net/ref/proxy.addr/

My use case is for the TCP listener; something like:
```
proxy.addr = :10001-10100;proto=tcp
```
... to allow a range of ports

Regards,
Shantanu

**Comment by shantanugadgil** [comment]
Is this still of any use to folks? If not I can close out the issue!?

**Comment by tristanmorgan** [comment]
Hi @shantanugadgil , Have you looked at the dynamic TCP port proxy? [TCP Dynamic Proxy](https://fabiolb.net/feature/tcp-dynamic-proxy/). The structures for the proxy address look like they only support specific ports (not a range).
