### ISSUE TITLE
allow redirect host to be empty

### ISSUE THREAD

**Issue by holtwilkins** [fabiolb/fabio#533]
And use request host if redirect host is empty.

Something like

```
route add global-redirect :80 https://$path opts "redirect=301"
```

Was suggested in https://github.com/fabiolb/fabio/issues/455, and I'm filing this ticket in response to that one.

My use-case here is being able to redirect anything received on http to fabio to serve a 301 to the https endpoint of the same address you used to get to fabio in the first place.

Thanks!

**Comment by holtwilkins** [comment]
Hey @leprechau & @magiconair , I started working on this, and did something similar to https://github.com/fabiolb/fabio/pull/451/files to get the `$host` substitution going.

However, the issue I'm seeing now is that the `:80` part doesn't seem to work.  I.e. `route add mock :80/ https://a.com/ opts "redirect=301"` doesn't work, but `route add mock a.com:80/ https://a.com/ opts "redirect=301"` does.  So, it seems like a `/` as the source is fine, but if you throw a port in there, it's no longer a catch-all.  Ideas on how to rectify that part (other than just run a separate instance of fabio that has a single `/` rule)?

**Comment by holtwilkins** [comment]
Hey @leprechau & @magiconair , I figured out the missing bit, it was this line: https://github.com/fabiolb/fabio/pull/544/files#diff-416b5689da1c2696679b73504589fad3R362

Now this global http -> https redirect seems to work great, what do you think?

**Comment by leprechau** [comment]
@holtwilkins Sorry, just getting caught back up on things.  I'll try and get this reviewed soon.
