### ISSUE TITLE
Dynamically generate routes from SRV

### ISSUE THREAD

**Issue by postelrich** [fabiolb/fabio#536]
This is a great project. Is there any vision of expanding it in the future to route based on the DNS query? By this I mean taking advantage of `[service].service.consul` capability such that fabio could forward the request to the underlying service? Much like a replacement to the consul-template + nginx setup.

**Comment by leprechau** [comment]
I'm not sure I understand the request.  Fabio is a consul aware load balancer and should already be capable of replacing a consul-template/haproxy or consul-template/nginx setup for most purposes.  What exact feature do you feel is missing from fabio?

**Comment by postelrich** [comment]
@leprechau to use fabio, I have to register the service with tags that specify the endpoints the service can handle and fabio uses that list of tags to route. I'm asking if fabio could be extended to instead route by the service name registered with consul. 

For example, I have an http api service called `restaurant-service` that has various endpoints such as  `/`,  `/restaurants`, etc. I want to make an http request to the service via fabio by doing `http://myfabio.server.com:9998/restaurant-service`. So to hit the restaurants endpoint I could do `http://myfabio.server.com:9998/restaurant-service/restaurants`.

**Comment by leprechau** [comment]
I see.  That would put more dependencies on service names within consul that are largely irrelevant today.  Is there any reason you cannot add the required tags to existing services?

**Comment by postelrich** [comment]
Why are service names irrelevant? It's how I identify groups of the same service.

One reason the endpoint tag scheme doesn't work for me is that a lot of my services have overlapping endpoints for things like stats, health check, management.

**Comment by leprechau** [comment]
Today the service name is irrelevant to fabio because it's not used anywhere in the routing table.  There is no correlation to a service route and it's name in consul.

To the overlapping endpoints, that's not an issue that prevents the use of tags.  Take the following example.

Services:
```
service foo-stuff on 1.2.3.4:8000 provides /stats
service bar-stuff on 4.5.6.7:9001 provides /stats
```

Solution:
```
foo-stuff has tag `urlprefix-/foo strip=/foo`
bar-stuff has tag `urlprefix-/bar strip=/bar`
```

Requests to `<fabio>/foo/stats` will be routed to `1.2.3.4:8000/stats` and a request to `<fabio>/bar/stats` will be routed to `4.5.6.7:9001/stats`.  There is no dependency on the service name to route the request.

**Comment by postelrich** [comment]
Ah I see, yes I was asking if fabio could make use of the service name in the routing table. Might be irrelevant since the `strip` part of the tag would take care of what im looking for. Thanks!
