### ISSUE TITLE
urlprefix allow to ignore case

### ISSUE THREAD

**Issue by shantanugadgil** [fabiolb/fabio#542]
I am using Fabio version `1.5.9` with my proxy configured in `tcp+sni` mode.

When I define a backend with a `urlprefix:-ExampleDomain.com/`, it shows up in the routes table as `exampledomain.com/` (small case)

This makes the SSL connects fail as the "servername" parameter doesn't match the "CamelCase" of the backend.

Could Fabio not automatically convert the expected SNI field to small case?
OR
Could Fabio provide a way to compare with "ignore case"?

Thanks and Regards,
Shantanu

**Comment by shantanugadgil** [comment]
@magiconair any thoughts?

**Comment by leprechau** [comment]
Sorry to leave you hanging.  Having a look now.

**Comment by leprechau** [comment]
Maybe a larger question ... but why would host comparisons ever be case sensitive?

**Comment by shantanugadgil** [comment]
@leprechau

Thanks for looking into this.

I understand that the `servername` field need/should not be case sensitive, but my use case is that of an existing application which already has a sizable install base.

The case sensitive `servername` field is hard coded in the client software and we cannot do anything about it *immediately*, and so this workaround fix.
