### ISSUE TITLE
wrong use  function strings.HasPrefix() in file passsing.go

### ISSUE THREAD

**Issue by tpwow** [fabiolb/fabio#545]
func isServiceCheck(c *api.HealthCheck) bool {
	return c.ServiceID != "" &&
		c.CheckID != "serfHealth" &&
		c.CheckID != "_node_maintenance" &&
		!strings.HasPrefix("_service_maintenance:", c.CheckID)
}

=======
strings.HasPrefix(c.CheckID, "_service_maintenance:")

**Comment by leprechau** [comment]
Good catch.  Want to submit a PR?
