### ISSUE TITLE
Multiple fabio instances load balancing different set of services.

### ISSUE THREAD

**Issue by eliasbrange** [fabiolb/fabio#551]
Howdy! I have a question regarding if it is possible to use multiple fabio instances that serves requests to different sets of services? Say that I have four services, `SvcA`, `SvcB`, `SvcC`, `SvcD`. I want two fabios to route traffic to these in the following fashion.
```
fabio1:9999/svc1 -> SvcA
fabio1:9999/svc2 -> SvcB
fabio2:9999/svc1 -> SvcC
fabio2:9999/svc2 -> SvcD
```

So what I'm after is that one fabio should only pick up one set of services in consul, and one other fabio should pick up another set. Is that possible?

**Comment by magiconair** [comment]
You could probably use the https://fabiolb.net/ref/registry.consul.tagprefix/ feature for this and register `SvcC` and `SvcD` with a prefix other than `urlprefix-`. This assumes that the services are sharing the same Consul instance.

**Comment by eliasbrange** [comment]
Thanks. Did not find that when searching through the configuration options.
