### ISSUE TITLE
Fabio forcing response header keys upper case

### ISSUE THREAD

**Issue by john-jolet-q2** [fabiolb/fabio#552]
It looks like fabio is forcing custom response headers to start with a capital letter.  This is breaking our mobile application.

when i hit the container directly, i have a token: q2token.  when i hit the container through fabio, it's Q2token.  is there a config option to turn this off?

**Comment by magiconair** [comment]
This is the default behavior of the Go http package since HTTP headers are case-insensitive. Your mobile app needs to treat the header names case-insensitive.
