### ISSUE TITLE
Question: does fabio block when writing access log messages?

### ISSUE THREAD

**Issue by ketzacoatl** [fabiolb/fabio#570]
Question: I have a deployment where fabio sits between AWS ALB and some backend services. We have several different environments, and frequently review access logs in Dev/etc. The question of whether or not to enable access logs "by default" for production came up. Should I be concerned about blocking or similar performance implications from enabling access logging?

**Comment by leprechau** [comment]
The access log is written to `stdout` and should be very efficient.  I would only be concerned about performance in a VERY high load environment.

**Comment by ketzacoatl** [comment]
Where "VERY high load environment" == 100's of thousands of requests per second? or 10's?

Thanks for the info and feedback.

**Comment by leprechau** [comment]
I'd want to split load between multiple fabio processes for either of those loads for resiliency if nothing else ... with access logging enabled you would want to validate that how you are capturing stdout from the fabio process is capable of keeping up with the required IOPs generated via the access logging.

**Comment by ketzacoatl** [comment]
yea, I think it'd be best to run load tests to confirm how well the IO is processed and how much is too much before the underlying system blocks fabio. Thanks for the feedback!

I'll close this for now, and maybe be able to post results if we are able to run those tests.
