### ISSUE TITLE
tcp+sni route with allow=ip:something does not seem to work

### ISSUE THREAD

**Issue by KEZHwMlXV1vFzs6QvY8v5WjX5** [fabiolb/fabio#576]
I added routes like this:

+ route add from.intern.net  from.intern.net/ http://10.0.1.3:30073/ opts "allow=ip:10.0.0.0/8"

Then from a host that is not in 10.0.0.0/8 I try a curl like this:

curl -v -k --resolve from.intern.net:443:$OUTEXTERNALIP https://from.intern.net

And fabio is happy to serve the request instead of denying it. Is this not compatible using tcp+sni? I thought that

https://github.com/fabiolb/fabio/blob/master/proxy/tcp/sni_proxy.go#L102

handled that?

**Comment by leprechau** [comment]
@KEZHwMlXV1vFzs6QvY8v5WjX5 I can't reproduce the issue locally.  I've created a branch with increased DEBUG level logging.  Could you build that branch and report the results?

**Comment by leprechau** [comment]
The branch is here:  https://github.com/fabiolb/fabio/tree/issue-576-ip-access

You should be able to checkout and `make` to build the binary.  If you're on a mac and deploying to linux you will need to run `make linux` instead.

**Comment by KEZHwMlXV1vFzs6QvY8v5WjX5** [comment]
yep it does not even arrive at that part of the code. From what I can see it already stops here

https://github.com/fabiolb/fabio/blob/faf228d1529f1b59a9d33e6c9cd42e365a937fe1/route/access_rules.go#L77

**Comment by KEZHwMlXV1vFzs6QvY8v5WjX5** [comment]
ok when I change the function to this it works for me.

```go
// AccessDeniedTCP checks rules on the target for TCP proxy routes.
func (t *Target) AccessDeniedTCP(c net.Conn) bool {
        addr := c.RemoteAddr().(*net.TCPAddr)
        ip := net.ParseIP(addr.IP.String())
        if t.denyByIP(ip) {
                log.Printf("[DEBUG] AccessDeniedTCP TRUE %s %s", ip, c.RemoteAddr().String())
                return true
        }
        log.Printf("[DEBUG] AccessDeniedTCP FALSE %s %s", ip, c.RemoteAddr().String())
        // default allow
        return false
}
```

**Comment by leprechau** [comment]
@KEZHwMlXV1vFzs6QvY8v5WjX5 Nice catch.  Doing the assertion to a `net.TCPAddr` pointer and checking the assertion is the correct.

**Comment by leprechau** [comment]
I pushed to the same branch and created https://github.com/fabiolb/fabio/pull/577
Let me know if that corrects the issue for you.

**Comment by KEZHwMlXV1vFzs6QvY8v5WjX5** [comment]
positive. It passed my checks.

**Comment by leprechau** [comment]
@KEZHwMlXV1vFzs6QvY8v5WjX5 awesome, I'll merge it.  Thanks again.
