### ISSUE TITLE
Fabio answer with 502 status code when a container is stopped

### ISSUE THREAD

**Issue by JeanBaptisteWATENBERG** [fabiolb/fabio#578]
Hi,

Fabio is answering with a 502 status code when one of registered docker container is stopped of killed. (this happen when docker swarm healthcheck fails) but consul healthcheck is still not updated. I reproduced the issue here : https://github.com/JeanBaptisteWATENBERG/fabio-blue-green-deployment
With 3 active and healthy container registered in consul, killing one of them is resulting in 502 status codes.
I would expect fabio to retry the calls on the 2 others healthy container, is it something planned ?

Thanks and regards,
Jean-Baptiste

**Comment by leprechau** [comment]
That's the current expected behavior.  When a container is stopped and there is no service registration and/or that service is unhealthy it will not be routed by fabio ... hence the 502 "Bad Gateway" response.

**Comment by leprechau** [comment]
I think this may be what you are wanting ... https://github.com/fabiolb/fabio/issues/511

**Comment by JeanBaptisteWATENBERG** [comment]
Hi
Thanks for your quick reply.
Sorry I submitted the issue a bit fast without providing a comment. I just editted the issue and provided some more context. As stated i was wondering whether Fabio could performed some retries on other containers to give time to consul to execute it's health check.

**Comment by leprechau** [comment]
@JeanBaptisteWATENBERG no problem, looking at your repo now.  Totally unrelated but if you want a command similar to `envsubst` with a few more features when templating you might checkout `sigil` ... it's what we've been using for awhile for that same task.  Hasn't been updated in awhile but it still works and does what it says ... https://github.com/gliderlabs/sigil

**Comment by leprechau** [comment]
Okay, I see what you are saying and currently the behavior is exactly as you have stated.  The "health" of a service is determined completely by consul and fabio honors what consul reports.  To avoid the problem you are describing you have a few options:

1.  Make the applications consul aware so they de-register when stopped
2.  Register the services with consul via something like `registrator` which will remove the service when the container is stopped
3.  Put the service instance in maintenance mode before stopping the container: https://www.consul.io/docs/commands/maint.html

**Comment by JeanBaptisteWATENBERG** [comment]
@leprechau It looks great, thank you very much ! I will have a look at those options and see whether i can catch the `sigterm` sent by docker swarm when updating services to unregister it in consul, i guess this is indeed the simplest solution. Thank you very much for your help :+1:

**Comment by leprechau** [comment]
@JeanBaptisteWATENBERG not a problem.  Let me know if you run into any issues or have additional questions.
