### ISSUE TITLE
HTTP 502 response half of the time

### ISSUE THREAD

**Issue by GoingFast** [fabiolb/fabio#584]
Some of the requests work, some dont. I'm using nomad. I have tagged my service with 
`	tags = ["urlprefix-/foo", "test-app"]	
`. Consul shows that everything is healthy. Sorry bit less information. I'm just looking into Nomad and trying out this loadbalancer and not experienced. Maybe someone can help me. Thanks

**Comment by GoingFast** [comment]
fabio is logging:
```
invalid log msg: 2018/12/08 20:49:57 http: proxy error: dial tcp 10.0.2.15:29526: connect: connection refused
invalid log msg: 2018/12/08 20:49:58 http: proxy error: dial tcp 10.0.2.15:21078: connect: connection refused
invalid log msg: 2018/12/08 20:49:58 http: proxy error: dial tcp 10.0.2.15:21078: connect: connection refused
invalid log msg: 2018/12/08 20:49:58 http: proxy error: dial tcp 10.0.2.15:21078: connect: connection refused
```
however I'm checking consul and they are healthy.

**Comment by pschultz** [comment]
What do the health checks do? Can you share the Nomad job specification?

What is `registry.consul.checksRequired` set to?

**Comment by GoingFast** [comment]
I figured it out. Consul was pointing to 10.0.2.15 its local and I have 3 node cluster on vagrant so it tried to access some random ports on local that arent existant. I had to put `address_mode = "driver"` to the nomad service and it got the right interface addresses. Thanks for trying to help btw @pschultz
