### ISSUE TITLE
Release date for 1.5.11

### ISSUE THREAD

**Issue by vinodbala** [fabiolb/fabio#592]
Hello Folks,

We are using Fabio's TCP+SNI routing feature and would like to also use IP based access control. While testing v1.5.10, we encountered the issue described in #576. I see that the issue is already fixed in #577 and have tested it privately. Could you please give an estimate on when the next Fabio version will be released ?

Thanks.

**Comment by sodabrew** [comment]
Fabio 1.5.11 was released in February 2019. All clear to close this issue?

**Comment by leprechau** [comment]
Yes, thank you!
