### ISSUE TITLE
Sidebar of the website is a little off

### ISSUE THREAD

**Issue by mildred** [fabiolb/fabio#599]
https://fabiolb.net/

"Features" is partly hidden on Firefox.

![image](https://user-images.githubusercontent.com/33804/52058454-bf214a80-2567-11e9-91e4-a519e2b15914.png)

**Comment by pschultz** [comment]
I cannnot reproduce this on Firefox 65. Are you sure you had scrolled all the way up before taking the screenshot?

**Comment by mildred** [comment]
Yes, but I checked again, and I cannot reproduce it with JavaScript enabled. However with JavaScript disabled, I have this problem.
