### ISSUE TITLE
[question] Release date for 1.5.11

### ISSUE THREAD

**Issue by mangy84** [fabiolb/fabio#601]
Hello,

We plan to use Fabio for GRPC protocol and we want to know when the next release (1.5.11 which contains GRPC support) will be available ?

Thanks

**Comment by shantanugadgil** [comment]
Same question, different reason :)
https://github.com/fabiolb/fabio/issues/592

I too am waiting for the new release! 😄

**Comment by tommyalatalo** [comment]
Also very interested in this, I don't know the history here, but I see many files already have the case for "proto=grpc" added. However you're saying it's not enabled in 1.5.10?

That would explain why I'm getting "[FATAL] 1.5.10. unknown protocol "grpc"" when trying to run a grpc proxy...

**Comment by mangy84** [comment]
Indeed, the documentation was updated but the version 1.5.10 doesn't have support for grpc. The commit for grpc support was made on master branch (the branch 1.5.10 doesn't contain this commit).

**Comment by tommyalatalo** [comment]
1.5.11 is out now

**Comment by leprechau** [comment]
Yes, 1.5.11 was released yesterday!  Thank you everyone for your patience.
