### ISSUE TITLE
This seems to be a recursive func call.  Is this correct?

### ISSUE THREAD

**Issue by galen0624** [fabiolb/fabio#625]
https://github.com/fabiolb/fabio/blob/3de70c7f0638b41ab37bddc399375f9af6d8074b/main.go#L519

**Comment by DukeyToo** [comment]
It is recursive, but only once - `defFormat` is the new format and it will be recognized on the second go around, and it will go through the `delta` switch case.

**Comment by galen0624** [comment]
@DukeyToo Ugg I missed that.  Thank you.
