### ISSUE TITLE
Changing Default Settings & Errors with compiling

### ISSUE THREAD

**Issue by kthecoder** [fabiolb/fabio#633]
**Using Linux 16.04LTS and Consul v1.4.4 and Docker v18.09.2**

Hi,

I have read the wiki a hundred times and I am still not quite sure what I am doing wrong.

I want to run fabio on a set of consul clusters with ip addresses's 172.20.x.x and for the life of me cannot figure out how to change the defaults.

**When I compile the program in linux it gives me**

? github.com/fabiolb/fabio/uuid [no test files]
Makefile:47: recipe for target 'test' failed
make: *** [test] error 1

**Also I have tried changing the 'fabio.properties'**
I tried setting registry.consul.addr = 172.20.40.x:8500
I tried setting registry.consul.register.addr = 172.20.40.x:8500

**I tried changing /config/default.go**
I tried changing it so the consul property was the ip address I wanted. Still didn't work.

**No matter what I try:**
The Fabio program continues to spit out:
[WARN] Error initializing backend. Get http://localhost:8500/v1/agent/self: dial tcp 127.0.0.1:8500: connect: connection refused

**Comment by leprechau** [comment]
The application should build fine if you are using golang 1.11+ and have enabled module support `GO111MODULE=on`.  To the consul issue, could you please provide the terminal output for exactly how you are running the application and the foreground output?
