### ISSUE TITLE
How to get Fabio service router table via consul?

### ISSUE THREAD

**Issue by fred214** [fabiolb/fabio#640]
Hi, I defined a service 'abc' in consul with tag 'prefix-/abc', forwarding works well.
And now I want to add 
    key: 'fabio/config',
    value: 'route add <svc><src> <dst> weight 1 opts "deny=ip:x.x.x.x/x"' 
for adding access control on router tables which generate automatically by service 'abc'.

I found that we can get route tables by **'http://host:9998/api/routes'**

**My question is ,How can I  to get router table list which generate by service via consul?** 
And that I can add router rules manually to overwrite the default.

**Comment by pschultz** [comment]
You seem to misunderstand how overrides work. The discovered routes and manual overrides are *not* merged. [You can only append to the discovered routes](https://github.com/fabiolb/fabio/wiki/Routing#manual-overrides) by specifying a complete rule. For instance:

    $ consul kv put fabio/config 'route add test-service /abc http://127.0.0.1:8025/ weight 1 opts "deny=ip:127.0.0.0/8"'

Alternatively, add the access control options to the Consul tag (e.g. `urlprefix-/abc deny=ip:127.0.0.1/8`).

Also, the computed routing table isn't written back to Consul, so there is no way to get it using the Consul API, if that is what you're looking for. Use the UI's `/api/routes` endpoint instead.

**Comment by fred214** [comment]
I also found that the routes adding by manual will not override the computed routes. But we can using 'weight 1' to achieved the expected effect. 
Thanks for your answer.
