### ISSUE TITLE
Wrong reported HealthCheck-URI using custom -proxy.addr & -ui.addr

### ISSUE THREAD

**Issue by ttais2017** [fabiolb/fabio#657]
When starting fabio with custom port numbers, i.e.:  fabio1.5.exe -proxy.addr :8888 -ui.addr :8887,  the health check URI reported to Consul is wrong.

Current output:
< Registered fabio with health check to "http://[my-private-ip]:9998/health >

BugFix:  the proxy.add parameter should be considered in the URL passed to Consul.

**Comment by pschultz** [comment]
I agree that setting ui.addr should change the default address for service registration. Until that is fixed specify the `-registry.consul.register.addr` flag explicitely:

    fabio1.5.exe -proxy.addr :8888 -ui.addr :8887 -registry.consul.register.addr :8887
