### ISSUE TITLE
Can fabio route request by request body

### ISSUE THREAD

**Issue by XiaoHanChina** [fabiolb/fabio#661]
What we need is when a POST request come, can fabio route request by request body.

like body `{"param":1111}` route to domain.com:8081
body `{"param":2222}` route to domain.com:8082

**Comment by leprechau** [comment]
No, fabio does not currently offer routing via any element in the body.  This doesn't sound like a job for a reverse proxy.

**Comment by XiaoHanChina** [comment]
I have seen a blog that makes nginx archive that via lua scripts. So I made this issue to ask is there any way for fabio.

**Comment by pschultz** [comment]
I agree that this is outside of fabio's scope.

Without scripting this isn't feasable because we'd have to invent some kind of complicated config language to target and match various request encodings.

I'm not aware of any mature package for embedded scripting in Go.

**Comment by XiaoHanChina** [comment]
Thank you.
