### ISSUE TITLE
Fabio Clustering.

### ISSUE THREAD

**Issue by orikalinski** [fabiolb/fabio#668]
Hello guys,

Can you please relate to #229? I wrote a comment there a week ago and still haven't got an answer.

Thank you,
Ori

**Comment by tino** [comment]
Please do not open a new issue if you don't get a response (in a timeframe you expected). Everybody working on fabio is volunteering their time. If you don't get a response, perhaps the question wasn't clear or not something others could relate too. Or perhaps you need a bit more patience as others were busy 😊.

**Comment by orikalinski** [comment]
My reply on #229 was a reply on a close issue. That's the reason I open a new one. I'm aware that everyone works here are volunteers. I believe that my question was clear enough 🙂

**Comment by leprechau** [comment]
@orikalinski What exactly are you trying to accomplish?  Why do you want to cluster Fabio?

**Comment by orikalinski** [comment]
I'm trying to get HA for my haproxy load balancer. The first instinct was to use floating ip. The issue that I'm using DigitalOcean which only provides public floating ip. I need to run over the private network hence that solution is not working for me. I tried to explore consul, and came across fabio. I tried to understand if I'm missing something and you can use a cluster of fabios, with the round robin distribution instead of the random one. In the #229 mentioned that running multiple fabio services willl do the job and I can only assume it will fit to those who need random distribution. Am I missing something?

**Comment by leprechau** [comment]
Sharing a virtual IP is going to be the most common solution for HA between hosts.  The DigitalOcean floating IP solution should be fine for this use case.

https://www.digitalocean.com/docs/networking/floating-ips/resources/#more-information

It appears that they support active/passive and the ability to only failure once a check has failed which would preserve round-robin routing within an "active" node.  You would only get a reset to that routing if a failover happened.

Outside of a vendor solution such as DigitalOcean's floating IP or a network layer solution like any cast BGP you could look at using OS level solutions like `keepalived`.  See the following article for an example:

https://tecadmin.net/ip-failover-setup-using-keepalived-on-centos-redhat/

**Comment by orikalinski** [comment]
Thank you for you response but as mentioned the floating ip implementation is not the problem, the issue with that is that DigitalOcean doesn't provide private floating ip but only public floating ip. Therefore, I was looking for an alternative.

Anyway, appreciate the response

**Comment by ketzacoatl** [comment]
@leprechau / @orikalinski / @nathanejohnson could this be closed?

**Comment by ketzacoatl** [comment]
@orikalinski, 

>  Therefore, I was looking for an alternative.

You could have DNS point at multiple public IPs, with fabio listening on each. Or you could use a LB from the cloud provider.

**Comment by nathanejohnson** [comment]
closing due to age
