### ISSUE TITLE
Unable to route to websites

### ISSUE THREAD

**Issue by satishviswanathan** [fabiolb/fabio#676]
I have multiple routes in my fabio routing tables with many services and a UI application. I can see fabio is forwarding the request correctly in the case of services but in the case of UI application the request is getting forwarded but all the resources of the web site is not getting downloaded.

Sample routing table
*********************

/myservice http://xxxx.xxx.com strip=/myservice
/uiapp http://yyy.yyy.com strip=/uiapp

In the case of uiapp I can see the index.html of the web application is hit bu the resources refered in the file are not getting downloaded.

For example

<link href="/static/main.88dc7d7ac8d00b6f86c1.css" rel="stylesheet">
All the href links are broken.

Any help on this issues is highly appreciated.

**Comment by pschultz** [comment]
Presumably the resource paths don't start with /uiapp. If that's a case you have to find a way to make "uiapp" do that or change the routing rules. Since you are using different domains it seems unnecessary to specify the path prefixes, for instance.

**Comment by satishviswanathan** [comment]
The reason I have the prefix /uiapp is that I have different services and web apps in by routing table and I need to differentiate by apps. Hence in this case I added the prefix /uiapp and added a strip for the same prefix. Please let me know if you are seeing any issue with this approach.

**Comment by pschultz** [comment]
fabio doesn't rewrite the response bodies for you, so you have to get "uiapp" to produce correct URLs. Your options are:

1. use a unique domain and stop rewriting the path
1. make the app produce absolute URLs with the /uiapp prefix
1. make the app produce relative URLs
1. add some other proxy that's capable of rewriting URLs in response bodies

Whether options 2 and 3 are possible depends on the app you are proxying; it has to let you configure the base URL.

I always recommend not messing with the request path (i.e. option 1), precisely because of issues like this.

**Comment by satishviswanathan** [comment]
Thank you for your quick responses.

Currently I do have relative URLs in the main.html file like 

"link href="/static/main.88dc7d7ac8d00b6f86c1.css" rel="stylesheet"

But this file doesn't get downloaded.

Option 1: use a unique domain and stop rewriting the path

Does that mean I should be using the redirect option of Fabio?

Option 2: make the app produce absolute URLs with the /uiapp prefix
I am using a open source web app which I'm trying to host it internal to my network. Hence I was trying to avoid any changes to it, also the paths seems to be relative too.

**Comment by pschultz** [comment]
> > Option 1: use a unique domain and stop rewriting the path
>
> Does that mean I should be using the redirect option of Fabio?

No. It means to change your route as follows:

```diff
-/uiapp http://yyy.yyy.com strip=/uiapp
+/ http://uiapp.yyy.yyy.com
```

Which domain you choose is irrelevant, of course, as long as it doesn't conflict with any other route.
