### ISSUE TITLE
Fabio/Consul route integration

### ISSUE THREAD

**Issue by kewinbrand** [fabiolb/fabio#689]
Hey I'm new to Fabio and Im not sure if I totally understood Fabio's route registering mechanism.
Consul let me register services in and obviously discover them. With that in mind, what's the point on have to tell to Fabio the service port up on adding a route that given service is running? Shouldn't I just add a route by its service name and Fabio automatically discover the port in Consul?

Thank you for your patience

**Comment by leprechau** [comment]
Fabio does read the address and port of the service for the destination (backend).  The frontend route however is not.  That is the purpose of the urlprefix tag.

**Comment by kewinbrand** [comment]
Oh now I see. For some reason I completely ignored the part 4 of the quickstart. 
I couldn't find in the documentation how Fabio does load balancing: is it by urlprefix or by service name?
