### ISSUE TITLE
urlprefix-zzz.xxx.com/api  not work

### ISSUE THREAD

**Issue by zzxap** [fabiolb/fabio#693]
urlprefix-zzz.xxx.com/api  not work
shows
No route for urlprefix-zzz.xxx.com:9999/api  

but
urlprefix-/api  works

why?

**Comment by shantanugadgil** [comment]
The thing that comes after `urlprefix-` is for paths only amd not domainname.

That's how I have always used it in L7 mode.

**Comment by zzxap** [comment]
how to make work with domain route

**Comment by JamesJJ** [comment]
> urlprefix-zzz.xxx.com/api not work
> shows
> No route for urlprefix-zzz.xxx.com:9999/api

The syntax you are using seems correct, however, your rule does not include `:9999` port.

Could you try:
```
urlprefix-zzz.xxx.com:9999/api
```

(or ensure the `Host` header of the request does not include `:9999`)

**Comment by zzxap** [comment]
urlprefix-zzz.xxx.com:9999/api work thaks
