### ISSUE TITLE
Fabio UI not displaying when hit on a DNS name

### ISSUE THREAD

**Issue by pvandervelde** [fabiolb/fabio#712]
We're upgrading to Fabio 1.5.12 from 1.5.11. There are three instances of Fabio running which all respond to the same DNS name (via DNS round robbin), i.e. the DNS name our.proxy.example.com points to the IP addresses of the three fabio instances.
With 1.5.11 the UI displays as expected. With 1.5.12 it is broken, but only in Firefox and only if you hit the 'shared' DNS name. If you hit one of the IP addresses directly it works just fine. 

If you hit the UI via the DNS name it looks like this:
![fabio-via-dns-name](https://user-images.githubusercontent.com/96201/66724855-5b397a80-ee87-11e9-8cc7-8fc88283dd7c.png)

but if you hit the IP address directly it looks like this
![fabio-via-ip](https://user-images.githubusercontent.com/96201/66724863-65f40f80-ee87-11e9-93d6-48b6e15e06ee.png)

In Chrome both look normal

This is in Firefox 69.0.2 on Windows 10

**Comment by leprechau** [comment]
Could you provide more information via the Firefox developer tools?  Which resource is failing to load?

**Comment by pvandervelde** [comment]
Actually I can't reproduce this at the moment :( I think overnight the caches cleared or Firefox had a change of mind or gremlins ... I shall close this ticket. Thanks for humoring me.
