### ISSUE TITLE
Very frequent 502 errors 

### ISSUE THREAD

**Issue by ansrivas** [fabiolb/fabio#721]
Hi, this is exactly the same issue as #716  and somewhat similar to #704 
Fabio Version: v1.5.12

Logs look like this:
```
invalid log msg: 2019/11/18 08:43:01 http: proxy error: read tcp 10.0.4.14:35712->10.0.4.9:29897: read: connection reset by peer
```
The requests do not reach the API and unfortunately result in `502`.

I also skimmed through other similar issues, I can also confirm that 
- there is no new deployment on Nomad
- health checks were fine

Edit: More info.

**Comment by leprechau** [comment]
@ansrivas What was the resolution here?

**Comment by ansrivas** [comment]
@leprechau unfortunately couldn't reproduce this deterministically with fabio.

As it kept happening frequently, had to switch to another loadbalancer due to the criticality of the issue.

**Comment by leprechau** [comment]
@ansrivas Understood, and thank you for responding.
