### ISSUE TITLE
 consul: Error fetching config from /fabio/config. Get 

### ISSUE THREAD

**Issue by zzxap** [fabiolb/fabio#729]
2019/12/02 11:31:33 [WARN] consul: Error fetching config from /fabio/config. Get http://47.24.29.17:8500/v1/kv/fabio/config?consistent=&index=925591&recurse=: EOF
2019/12/02 11:33:34 [WARN] consul: Error fetching config from /fabio/noroute.html. Get http://47.24.29.17:8500/v1/kv/fabio/noroute.html?consistent=&index=925591&recurse=: EOF

**Comment by dcarbone** [comment]
@zzxap: doesn't look like there is anything binding port 8500 on that ip.  please ensure you've configured consul correctly.
