### ISSUE TITLE
GRPC Proxy + HTTP Proxy, both useable at the same time?

### ISSUE THREAD

**Issue by systemfreund** [fabiolb/fabio#734]
Since the gitter channel seems to be closed, I'm asking here.
When I start fabio with `-proxy.addr=:1234;proto=grpc` does it mean that it is only operating in "grpc-mode"?
Do I have to start a second instance when I want regular http proxying, too?

The documentation is not quite clear about it, perhaps it can be improved.

**Comment by tristanmorgan** [comment]
on the cli you can add multiple listeners by comma separating. 
eg. `-proxy.addr=:1234;proto=grpc,:9999;proto=http`

**Comment by systemfreund** [comment]
Thanks, it is indeed documented already. So nothing needs to be done here :)
