### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by magiconair** [fabiolb/fabio#735]
All good things come to an end. 

## History 

Fabio started as a small 350 line load-balancing experiment during my time at eBay in Amsterdam to replace our insane load-balancer setup and worked much, much better than I expected. It made routing dirt simple and pushed the responsibility for the route to the service instead of coordinating releases between micro-services and the DevOps team.

It also hit some sweet spot for the HashiCorp Consul users which now had a super-simple consul-enabled load balancer and HashiCorp noticed very quickly. 

This was 2015, with go1.5 and consul 0.7. My team was the largest Go team in Amsterdam and to the best of my knowledge we were the only ones running large scale, big money, production critical stuff on Go. Very exciting times. 

Fabio would have probably never seen the light of open-source, if there wouldn't have been @emilevauge with https://github.com/containous/traefik and my colleagues pushing me to open-source Fabio. I got mocked for the choice of name (b/c of the italian actor) but that died off quite quickly when the Github stars were flying in. Emile and I even met briefly during a Go conference in Paris where I presented the project for a couple of minutes. Fun times and some healthy competition ;)

I've added features that were helpful to us and others. Was involved in long-winded discussions in what should and should not be in the project and probably neglected to build a more active community of committers around the project. Maintaining an open-source project is a lot of work. It does not get easier if it becomes somewhat successful.

For a long time Fabio had a leg on HAProxy because of reloads without restarts. For an even longer time it had one on Traefik because of the TCP proxy with SNI support. (https://github.com/containous/traefik/issues/933). I remember writing that code, forking the Go TLS code and getting something working in a couple of lines which was so useful.

## You are all awesome!

Joyent added features to Fabio like the grpc-proxy and countless contributors have found bugs, workarounds, fixes, features, improvements and the project has become bigger and more successful than I could have ever imagined. 

With 10 million Docker pulls Fabio seems to be driving some serious websites. I got insane performance numbers with Fabio running on a 24-core machine from some companies where Fabio replaced an expensive load-balancer for free. 

But times change, @emilevauge went ahead and built @containous around traefik, [HAproxy](https://haproxy.org) can handle reloads without restarts and [Caddy](https://caddyserver.com) with the awesome auto-TLS came along. 

I've got an offer to turn Fabio into a company and turned it down, then worked for HashiCorp for a while and left again, now working full time on batteries and injecting Go into the industrial manufacturing industry. 

I've moved on - mentally - and also in terms of my commitment. Without the extraordinary help of @leprechau and @pschultz over the last year the project would be in much worse shape. 

I think it is time to let go and find **a new maintainer**. If we can't find one then this project needs to go to the software graveyard.

I've never done this before so I'm curious who would be interested and what to look out for. 

Thank you all!!!

Frank Schröder/@magiconair

**Comment by leprechau** [comment]
@magiconair I've reached out to the larger organization here at ENA about taking Fabio maintenance on in an official capacity within the development team.  We're currently in discussion and I probably won't know anything till after the first of the year given the holiday schedules.

I also sent you an email with a bit more context.  I'll be on PTO after next week but will be available via email if you need to contact me.

Thank you again for all you have done with Fabio over the years.  This project has been and still is critical to our application stack and development workflow.

**Comment by magiconair** [comment]
Dear Fabio Community,

I am more than happy to announce that https://github.com/fabiolb/fabio has a new maintainer.

Aaron Hurt (@leprechau) and his team will maintain fabio from now on.

Aaron has already been a core maintainer over the last year and the project couldn't have landed in better hands.

I wish Aaron and his team success and want to thank the entire community for the last 5 years!

Frank
