### ISSUE TITLE
Is it possible to create cluster of fabio?

### ISSUE THREAD

**Issue by sidvanarse** [fabiolb/fabio#736]
Can we use fabio as gateway service? And is it possible to create cliuster of fabio?

**Comment by leprechau** [comment]
@sidvanarse Could you please explain what you mean by "gateway service" a bit more?

To clustering, there isn't any state sharing between multiple fabio instances.  However, you absolutely can run multiple instances of fabio spread across different hosts pointing towards the same consul cluster instance.  We deploy fabio along with quagga (https://www.quagga.net) and leverage anycast BGP (https://en.wikipedia.org/wiki/Anycast) to load balance traffic to a single internet address across the hosts.

**Comment by leprechau** [comment]
There are also other tools such as keepalived or ucarp to manage VIPs (virtual IPs) across hosts within the Linux ecosystem.

**Comment by leprechau** [comment]
If the above explanation didn't resolve your issue, please feel free to re-open this issue.
