### ISSUE TITLE
Authentication issue.

### ISSUE THREAD

**Issue by sidvanarse** [fabiolb/fabio#743]
I have set up secure HTTPs fabio as follows:

cs=cert;type=file;cert=path/a-cert.pem;key=path/a-key.pem;clientca=path/clientAuth.pem

I have backend https service running on port 8060 with /getToken end point, which requires client authentication.  If i directly access https://localhost:8060/getToken peer certificate is sent to the https service and i am able to get peer cert information at backend.

When i access https://localhost:9999/getToken in browser i get bad certificate error in fabio console. Fabio is not forwrding peer certificate(client certificate) to my back end service. 

It is very common to have HTTPs service which needs client authentication. How can i forward peer certificate info to my backend service.  I use username from peer certificate to authenticate whether user can perform certian taks or not.

**Comment by tristanmorgan** [comment]
I may be wrong here but maybe the listener (as configured by proxy.addr) should be configured as either TCP or TCP+SNI (not https) that way the client certificate you present is passed through to the backend?

**Comment by pschultz** [comment]
As I was saying in #738 already, you have to use a TCP proxy if you want fabio's client to authenticate to a backend with TLS. fabio can't possibly "forward the certificate" if it terminates TLS, because it doesn't have access to the private key.

Closing as duplicate.
