### ISSUE TITLE
Port with path routing

### ISSUE THREAD

**Issue by evheny0** [fabiolb/fabio#748]
Hi!

Is there any way to add port and host/path to routing simultaneously? Here is an example:

```
urlprefix-example.com:5000/
```
I've added listener for 5000 port to `proxy.addr` config, but it doesn't work anyway.

Thanks!

**Comment by evheny0** [comment]
Seems like it's not possible with tcp since protocol doesn't have anything except ip and port

**Comment by leprechau** [comment]
@evheny Sorry for the delayed response.  Routing by host and path is only available with a `http` or `https` listener.  The `tcp` listener only routes on ip and port.  The `tcp+sni` listener however can route based on ip:port as well as host contained in the SNI header sent in the client hello.
