### ISSUE TITLE
Should rewrite the Host Header 

### ISSUE THREAD

**Issue by smancke** [fabiolb/fabio#75]
Following the HTTP1.1 spec, rfc2616-sec14, 
a proxy has to rewrite the host header:

> An HTTP/1.1 proxy MUST ensure that any request message
> it forwards does contain an appropriate Host header field
> that identifies the service being requested by the proxy.

This is also, how e.g. nginx behaves.
And it is needed, if the upstream server are using a virtual host configuration.

Here there is a possible fix for it:
https://github.com/smancke/fabio/tree/proxy-header-handling

And we had already some discussion about that in #72

**Comment by manos** [comment]
+1
I'm trying to add a route for /favicon.ico -> www.domain.com/ and www.domain.com is fronted by cloudfront. If it doesn't get Host: www.domain.com, it can't serve favicon.ico for me.

Perhaps a workable solution here would be adding opts "host=www.example.com" to the route -- if it supported that :)

**Comment by manos** [comment]
@magiconair does the above comment make sense?

**Comment by magiconair** [comment]
Hi @manos , sorry for the delay. I was on vacation for a couple of weeks and I'm catching up now. I think what you're suggesting makes sense.

**Comment by krjensen** [comment]
+1
This is needed if you are using microsoft IIS and route based on Host header.

**Comment by magiconair** [comment]
@manos the `host=www.domain.com` option has been added with #294

**Comment by ragunathp** [comment]
Hi,
Is this feature available in 1.5.2? Based on the document reference  https://github.com/fabiolb/fabio/wiki/Routing#manual-overrides, it seem to be available with the option for "host=name".  Could you please confirm?

My use case is to configure docker HRM endpoint in fabio and I face the issue.
Works fine when I do,  curl -H 'Host: xyz.docker-hrm.example.com" http://fabio-ip:9999/app/somepath 
But the issue exists while hitting from browser http://fabio-ip:9999/app/somepath.
Option configured in fabio as "strip=/app host=xyz.docker-hrm.example.com"
The '$request_host' in fabio is not changed to 'xyz.docker-hrm.example.com'
Is it something I am missing?

**Comment by magiconair** [comment]
This has been fixed in #375 which is currently on master. I'll cut a 1.5.3 today to roll this out since the metrics refactor is going to take longer.

**Comment by ragunathp** [comment]
Thank you looking forward for  1.5.3 release.

**Comment by magiconair** [comment]
So the `host=dst` option implements the original desired behavior. `host=dst` was added with #294. In addition to `host=dst` you can use `host=www.mydomain.com` to set the exact host header.

1.5.3 is released
