### ISSUE TITLE
[Question] What are opinions on allowing stale reads of Consul Catalog

### ISSUE THREAD

**Issue by ddreier** [fabiolb/fabio#764]
I'm curious about folks' opinion on allowing Fabio to make stale reads for the Consul Catalog backend. Currently Fabio is hard-coded to require consistent reads, which causes any request to go to the current leader in the Consul cluster.

In order to try to reduce load on our Consul leaders, we're testing out several changes to the way we run Fabio. This includes switching Fabio to perform stale reads so that the read load can be spread across all of the Consul servers.

A little info about our environment: We run several Nomad/Consul/Vault clusters the largest of which has about 1500 Consul Services and around 200 Fabio instances averaging several thousand routes. One of the Fabio "pools" has almost 10k routes.

If the maintainers are amenable to it I'd be happy to open a PR to add a config option for stale reads.

Thanks!

**Comment by scalp42** [comment]
Leader elections is an issue as well. Being able to allow stale reads would fix the issue.

**Comment by scalp42** [comment]
PR is #811 which prevents Fabio from dropping routes on leader election.

**Comment by leprechau** [comment]
@scalp42 see it, thank you. Going to close this question as the discussion appears to be in #811.
