### ISSUE TITLE
How to disable client authentication for https?

### ISSUE THREAD

**Issue by vilva42** [fabiolb/fabio#765]
We are planning to replace a load balancer with Fabio. In our current setup, the load balancer terminates SSL and the client hitting the LB doesn't present a certificate. With Fabio, we get the following error
`http: TLS handshake error from 127.0.0.1:44846: tls: client didn't provide a certificate`

Is there a way to disable client authentication or a workaround?

**Comment by arj22** [comment]
If I remove [this line](https://github.com/fabiolb/fabio/blob/c034d4fae1d604adbb5ff98034cad138eab3a771/cert/source.go#L141) from the code, I'm able to curl it

**Comment by vilva42** [comment]
If I remove [this line](https://github.com/fabiolb/fabio/blob/c034d4fae1d604adbb5ff98034cad138eab3a771/cert/source.go#L141) from the code, I'm able to curl it

**Comment by nathanejohnson** [comment]
This should only get hit if you provide client CA's?

**Comment by vilva42** [comment]
We were running into this error even when the client CA wasn't being provided. I don't have the environment anymore to reproduce the error, so closing this issue.
