### ISSUE TITLE
Add arm64 arch

### ISSUE THREAD

**Issue by analytically** [fabiolb/fabio#804]
Currently there is no arm64 download available for Fabio.

**Comment by nathanejohnson** [comment]
There should be nothing preventing fabio being built from source for arm64 - except on Big Sur running Apple silicon.  I realize now with apple shipping m1 macs and raspberry pi's gaining popularity it would be good to have a release build available for download.  I will plan to add this once the golang toolchain works properly on apple's m1 chip.  Hopefully I should have some hardware incoming to test on.

**Comment by loafoe** [comment]
Any update on this? With `m1` and `rpi4s` being quite widespread now it would be great to have a multiarch docker release for `arm64`. Thx!

**Comment by lanefu** [comment]
@loafoe  here's an entrypoint script i use in a golang container

```
 
    apt update
    apt install curl gnupg build-essential rclone zip -y
    rclone -q config create b2 b2
    mkdir -p /go/src/
    cd /go/src/
    git clone https://github.com/fabiolb/fabio.git
    cd fabio
    for ARCH in arm64 arm amd64; do
      export GOARCH=${ARCH}
      go build -v
      mv fabio fabio-${ARCH}
      rclone copy fabio-${ARCH} myobjecstorage:artifacts/fabio/
    done
 ```
