### ISSUE TITLE
fabio binary filename for download

### ISSUE THREAD

**Issue by shantanugadgil** [fabiolb/fabio#805]
Is there any particular advantage with having the Golang version as part of the file name?
_(I know once there were builds using two separate Golang versions)_

as of now my automation has this ...
```
fabio:
        $(WGET_CMD) https://github.com/fabiolb/fabio/releases/download/v$(FABIO_VERSION)/fabio-$(FABIO_VERSION)-go$(FABIO_GOLANG_VERSION)-linux_amd64 -O fabio-$(FABIO_VERSION)-go$(FABIO_GOLANG_VERSION)
        sudo chmod 0755 fabio-$(FABIO_VERSION)-go$(FABIO_GOLANG_VERSION)
        sudo chown root:root fabio-$(FABIO_VERSION)-go$(FABIO_GOLANG_VERSION)

```

Just wondering if this can be simplified just to have the fabio version?

**Comment by nathanejohnson** [comment]
@shantanugadgil what is the use case?  This would require a fairly small number of changes, and I would tend to agree that the go version isn't terribly relevant to the filename when we're only using one go version to do the build these days.  On the other hand, I'm not sure this impacts package maintainers since they will probably be using the source tarball anyway?  What pain does this cause you specifically?

**Comment by shantanugadgil** [comment]
No major pain, as my Makefile is already setup using the variables (as I mentioned).

The use case is just for simplicity, not super important, just have to keep updating two variables instead.of one. 🙂

**Comment by nathanejohnson** [comment]
so followup question: what are you packaging this for?  I've been thinking that releasing an rpm or deb would be useful

**Comment by shantanugadgil** [comment]
> 
> 
> so followup question: what are you packaging this for? I've been thinking that releasing an rpm or deb would be useful

Nothing. I just consume it. 🐒 

I just happen to use a GNUmakefile to download various tools 🙊 , Fabio is one of them.

**Comment by shantanugadgil** [comment]
> 
> 
> so followup question: what are you packaging this for? I've been thinking that releasing an rpm or deb would be useful

forgot to mention that day ... do you know of FPM? (https://github.com/jordansissel/fpm) to create the packages.

**Comment by nathanejohnson** [comment]
the project uses goreleaser, which does support creating packages in several popular formats.  I might look into doing this for the next release.
