### ISSUE TITLE
Using Fabio with Consul over mTLS

### ISSUE THREAD

**Issue by sjiveson** [fabiolb/fabio#820]
Hi,

I'm trying to use Fabio with Consul over mTLS, however, despite setting these in **fabio.properties**:

```
registry.consul.addr = 172.17.0.1:8501
registry.consul.scheme = https
registry.custom.scheme = https
registry.consul.tls.keyfile = /secrets/consul-client.key
registry.consul.tls.certfile = /secrets/consul-client.pem
registry.consul.tls.cafile = /secrets/ca.pem
registry.consul.tls.capath = /secrets
registry.consul.tls.insecureskipverify = true
```

Fabio continues to attempt to communicate with Consul using HTTP and I see this error message repeatedly:

`2021/02/26 16:06:08 [WARN] Error initializing backend. Unexpected response code: 400 (Client sent an HTTP request to an HTTPS server.)`

I don't see any further settings related to this anywhere (and actually `registry.consul.scheme = https` isn't even in the documentation that I know of). I've checked: https://github.com/fabiolb/fabio/blob/master/fabio.properties. I've also had a look at this: https://github.com/fabiolb/fabio/pull/602/files#diff-e16ec0f468476b8e8ac19b72eec5a0e2e05fbd774cbd6216577a7102bcb4d2f1 but I'm none the wiser on what I might be missing. Any ideas?

Thank you.

**Comment by jamesdmorgan** [comment]
I'm having the same issue

**Comment by larryon** [comment]
try using registry.consul.addr = https://172.17.0.1:8501

**Comment by sjiveson** [comment]
That did the trick, thank. you.
