### ISSUE TITLE
[question] - Can Fabio listen on 80/tcp with Nomad

### ISSUE THREAD

**Issue by replay111** [fabiolb/fabio#844]
Hi,

I am experimenting with Nomad cluster and so far everything looks fine apart one thing - I do not know how to reconfigure Fabio to listen on port 80 instead of 9999.
I am running with Nomad and I was trying to redefine ports this way:

```
    network {
      port "lb" {
        static = 80
      }
      port "ui" {
        static = 9998
      }
    }
```

but it looks like Fabio by default listen on 9999 - can this be changed?

**Comment by tristanmorgan** [comment]
Something like this wuld have fabio listening on your static LB port. 
```
      env {
        FABIO_proxy_addr                       = ":${NOMAD_PORT_lb};proto=http"
      }
```

**Comment by replay111** [comment]
This is awesome ;-) I totally forgote that I can pass envs ;-)
Works like a charm - thanks for help!
