### ISSUE TITLE
JSON schema is incorrect in website Dest should be Dst

### ISSUE THREAD

**Issue by webmutation** [fabiolb/fabio#852]
https://fabiolb.net/ref/registry.backend/

The custom JSON schema field dest is incoorect it should be dst, I am currently trying to write a bridge for K8S services that are not descoverable by Consul due to lack of health checks and came across this issue

```
[
 {
  "cmd": "string",
  "service": "string",
  "src": "string",
  "dest": "string",
  "weight": float,
  "tags": ["string"],
  "opts": {"string":"string"}
 }
]
```

Should be dst... also would be useful to have some descriptions for the fields, I would gladly make a PR but I did not find the source code for the website...

**Comment by tristanmorgan** [comment]
it looks like docco is on the gh-pages branch...

**Comment by webmutation** [comment]
thanks, ill do a PR

**Comment by webmutation** [comment]
I have opened https://github.com/fabiolb/fabio/pull/854 but I am not sure who is maintaining this project right now.
