### ISSUE TITLE
Custom behavior for the situation when the service has no healthy instances

### ISSUE THREAD

**Issue by Duskone39** [fabiolb/fabio#898]
Hello everyone, please forgive me right away if my question is stupid or the answer has already been written before (I can’t find it, but I was looking for it). Is it possible in fabio to set a route to which the request will be redirected if there are no available services?

I mean the situation when services are registered for a certain path, but they have the status "unhealthy". In such a situation, I would like to redirect requests to a static page with information like "technical work is in progress, try again later". 

Is there a way to do this with consul+fabio ?

**Comment by leprechau** [comment]
You can do this using the weight feature ...
https://github.com/fabiolb/fabio/issues/42
https://fabiolb.net/cfg/

**Comment by Duskone39** [comment]
> 

Thanks amazing solution
