### ISSUE TITLE
windows: setting logging path in fabio properties

### ISSUE THREAD

**Issue by lcividinwork** [fabiolb/fabio#920]
Hi There am I able to set log to a logging path (for example d:\fabio_logs\fabio.log). We have some windows nomad hosts that are running fabio as a windows service. 

Reading the fabio.properties, it only offers stdout which is screen in windows (unless I'm mistaken, often am) and not that helpful.

**Comment by nathanejohnson** [comment]
It is possible to redirect standard output to a file on Windows, just as it is on *nix.  Does this get you what you need?  But you are correct, the only logging output currently supported is stdout.

**Comment by nathanejohnson** [comment]
@lcividinwork you're welcome!  And, as always, PR's welcome!
