### ISSUE TITLE
certificates - cert and ca chain/intermediate

### ISSUE THREAD

**Issue by replay111** [fabiolb/fabio#946]
Hi,

I have my own PKI and I want to add certificate with chain:

CA Cert (trust) -> Intermediate -> Server Cert + Server Cert.Key

But when I am exposing server.cert + server.cert.key as bundle .pem my browser claims that connection is not secure... (CA Trust is added)

How can I add cert chain to show the path to correct CA Trust for browser?

Best Regards
Replay

**Comment by aaronhurt** [comment]
It's common practice to just concatenate all of those together. Example ...
```
cat your-cert.pem intermediate-cert.pem ca-cert.pem private-key.pem > combined.pem
```
and configure the listener with the combined pem file.

**Comment by replay111** [comment]
hm... I think I did that - but I got error that private key does not match certificate... I will re-try today with this order, maybe this was incorrect...

**Comment by replay111** [comment]
@aaronhurt Thanks a lot - a messed up with order :/ 

Now it is working like charm :D
