### ISSUE TITLE
Fabio not exporting all the metrics with prometheus

### ISSUE THREAD

**Issue by fragstein** [fabiolb/fabio#947]
Hi,
I decided to use prometheus metrics instead of statsd ones. The problem is that, when I go to /metrics I can see metrics that are not related to fabio service, routes etc (as it was with statsd).

` o_gc_duration_seconds{quantile="0"} 8.3543e-05
 go_gc_duration_seconds{quantile="0.25"} 0.000145657
 go_gc_duration_seconds{quantile="0.5"} 0.000181929
 go_gc_duration_seconds{quantile="0.75"} 0.000262514
 go_gc_duration_seconds{quantile="1"} 0.214905523
 go_gc_duration_seconds_sum 1.671132568
 go_gc_duration_seconds_count 2122
 go_goroutines 724
 go_info{version="go1.19.4"} 1
 go_memstats_alloc_bytes 1.4096576e+07
 go_memstats_alloc_bytes_total 2.5650460504e+10
 go_memstats_buck_hash_sys_bytes 1.64461e+06
 go_memstats_frees_total 1.52870777e+08
 go_memstats_gc_cpu_fraction 0.006833858649980704
 go_memstats_gc_sys_bytes 1.002656e+07
 go_memstats_heap_alloc_bytes 1.4096576e+07
 go_memstats_heap_idle_bytes 2.2380544e+07
 go_memstats_heap_inuse_bytes 1.982464e+07
 go_memstats_heap_objects 55384
 go_memstats_heap_released_bytes 1.163264e+07
 go_memstats_heap_sys_bytes 4.2205184e+07
 go_memstats_last_gc_time_seconds 1.722931917146408e+09
 go_memstats_lookups_total 0
 go_memstats_mallocs_total 1.52926161e+08
 go_memstats_mcache_inuse_bytes 9600
 go_memstats_mcache_sys_bytes 15600
 go_memstats_mspan_inuse_bytes 387072
 go_memstats_mspan_sys_bytes 569520
 go_memstats_next_gc_bytes 2.6186432e+07
 go_memstats_other_sys_bytes 2.011366e+06
 go_memstats_stack_inuse_bytes 8.126464e+06
 go_memstats_stack_sys_bytes 8.126464e+06
 go_memstats_sys_bytes 6.4599304e+07
 go_threads 18
 process_cpu_seconds_total 374.8
 process_max_fds 1.048576e+06
 process_open_fds 642
 process_resident_memory_bytes 6.0358656e+07
 process_start_time_seconds 1.72293067492e+09
 process_virtual_memory_bytes 7.55576832e+08
 process_virtual_memory_max_bytes -1
 promhttp_metric_handler_requests_in_flight 1
 promhttp_metric_handler_requests_total{code="200"} 26682
 promhttp_metric_handler_requests_total{code="500"} 0
 promhttp_metric_handler_requests_total{code="503"} 0`
ver: 1.6.3
Is it something that i'm missing?
Thanks!

**Comment by tristanmorgan** [comment]
Hi @fragstein,
 
Most Golang programs expose these metrics as part of the github.com/prometheus/client_golang package. So the output is expected behaviour and they can be pretty useful. I don't think there is a way to turn them off.

Regards,
T.

**Comment by kaloyan-s** [comment]
Hello @tristanmorgan , 
But there are no other standard metrics, like with statsd - related to fabio service, routes, etc.
Do you have any idea about that ?

**Comment by tristanmorgan** [comment]
you're not seeing any like the following?

```
# HELP fabio__http_status 
# TYPE fabio__http_status histogram
fabio__http_status_bucket{code="200",le="0.005"} 19761
fabio__http_status_bucket{code="200",le="0.01"} 22761
fabio__http_status_bucket{code="200",le="0.025"} 25483
fabio__http_status_bucket{code="200",le="0.05"} 27148
fabio__http_status_bucket{code="200",le="0.1"} 27528
fabio__http_status_bucket{code="200",le="0.25"} 27644
fabio__http_status_bucket{code="200",le="0.5"} 27652
```

in my environment I have set the folowing to enable prom and setup the listener.
```
FABIO_metrics_target="prometheus"
FABIO_proxy_addr=":80;proto=http,:21883;proto=prometheus"
```

**Comment by fragstein** [comment]
Nope. Here is my config:
`             - name: FABIO_REGISTRY_CONSUL_ADDR
               value: "$(HOST_ADDRESS):8500"
             - name: FABIO_REGISTRY_CONSUL_REGISTER_TAGS
               value: "proxy.port:9999"
             - name: FABIO_PROXY_ADDR
               value: ":9999;proto=prometheus"
             - name: FABIO_METRICS_PREFIX            
               value: "fabio."
             - name: FABIO_METRICS_PROMETHEUSNAMETAGS
               value: "true"
             - name: FABIO_METRICS_NAMES
               value: "{{clean .Service}}"
             - name: FABIO_METRICS_TARGET
               value: "prometheus"  `

**Comment by tristanmorgan** [comment]
Do you have an http(s) listener?
Anything in the logs to give us a hint?

**Comment by fragstein** [comment]
That was the problem. I thought that http listener is by default and just added proto=prometheus as additional one.
Thanks!
