### ISSUE TITLE
CI pipeline to run testsuite

### ISSUE THREAD

**Issue by ketzacoatl** [fabiolb/fabio#949]
It would be nice if PRs could show the status of the testsuite and not need to be built locally to determine if the PR breaks functionality.

**Comment by aaronhurt** [comment]
It's more than past time to update the GitHub actions used on this project. I should have the bandwidth to take a stab at that over the long weekend.

**Comment by ketzacoatl** [comment]
@aaronhurt is there a shortlist of updates you have in mind?

**Comment by ketzacoatl** [comment]
AFAICT, @tristanmorgan's recent updates have resolved this
![image](https://github.com/user-attachments/assets/76ded4c8-7617-4a45-b0df-f453959a5b1b)
https://github.com/fabiolb/fabio/pull/952/checks
